### ISSUE TITLE
[Proxy] Allowing uppercase letters in channel name on channel creation #8563

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#100]
https://github.com/RocketChat/Rocket.Chat/issues/8563

**Comment by mrsimpson** [comment]
Implemented with 0.59 in RC-core. 

> In 0.59, there is a configuration option to allow special characters in the room-name:
Layout -> User Interface -> allow special characters...
> <img width="697" alt="room-name-setting" src="https://user-images.githubusercontent.com/17176678/31826104-73622840-b5b4-11e7-872b-d153ae45237f.png">
> <img width="936" alt="room-name" src="https://user-images.githubusercontent.com/17176678/31826105-73b75720-b5b4-11e7-9c44-ebdd2cc35221.png">

**Comment by janrudolph** [comment]
Thank you @mrsimpson !
