### ISSUE TITLE
Migrate settings from DBS_AI... to Assistify...

### ISSUE THREAD

**Issue by mrsimpson** [assistify/Rocket.Chat#103]
# Purpose
Have a consistent naming of all Assistify settings

# Description
There are setting used to integrate Smarti into RC which are named `DBS_AI...`. This is legacy code.
Since all dbs-packages have been removed, the settings' names should be changed as well.
Since this is a DB-change, a migration script is necessary. In this context, a description how to add custom migrations would be appreciated.

**Comment by janrudolph** [comment]
Done
