### ISSUE TITLE
Log file error - Exception from sub stream-room-messages

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#105]
`[34mI20171023-08:21:30.750(2) Exception from sub stream-room-messages id a49fcc2d-9734-4d8a-b8d5-6def75bcb0e0 Error: Match error: Expected string, got null   at exports.check (packages/check.js:56:15)   at [object Object].<anonymous> (/opt/Rocket.Chat/programs/server/packages/rocketchat_streamer.js:469:5)   at [object Object].<anonymous> (/opt/Rocket.Chat/programs/server/packages/rocketchat_lib.js:1129:15)   at packages/matb33_collection-hooks.js:307:21   at [object Object]._.extend.withValue (packages/meteor.js:1126:17)   at [object Object]._handler (packages/matb33_collection-hooks.js:306:28)   at maybeAuditArgumentChecks (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1858:12)   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:1181:16   at [object Object]._.extend.withValue (packages/meteor.js:1126:17)   at [object Object]._.extend._runHandler (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1180:51)   at [object Object]._.extend._startSubscription (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:1028:9)   at [object Object]._.extend.protocol_handlers.sub (/opt/Rocket.Chat/programs/server/packages/ddp-server.js:816:12)   at /opt/Rocket.Chat/programs/server/packages/ddp-server.js:754:85 `

Team: seec

**Comment by mrsimpson** [comment]
this also occurs on our server. However, not regularly. 
We should observe the exceptions and ask the complete team what they did "just now" when this re-occurs.
I recall we saw this on deletion of a channel.
