### ISSUE TITLE
Enhance configuration of Smarti for authentication (Smarti 0.6.1)

### ISSUE THREAD

**Issue by mrsimpson** [assistify/Rocket.Chat#106]
# Purpose
As 0.6.1 introduces authentication for all webservices, the Smarti-widget needs to provide a client specific auth token.

# Description
Provide a setting which is being passed to the Smarti-Wdiget on construction.

Depends on https://github.com/redlink-gmbh/smarti/issues/60

**Comment by janrudolph** [comment]
done
