### ISSUE TITLE
Request room names show different behavior than regular channels

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#109]
It is possible to allow special characters in a channel name. A channel might look this:

<img width="503" alt="rocket_chat_" src="https://user-images.githubusercontent.com/3596824/31931763-83396c4a-b8a4-11e7-9aad-2d4ac063c83e.png">

The request rooms behave differently. Here the specials chars are not displayed in the channel header and spaces are replaced by "-".

<img width="510" alt="rocket_chat_" src="https://user-images.githubusercontent.com/3596824/31931731-6d93cbba-b8a4-11e7-847b-85d3655ed588.png">

**Comment by mrsimpson** [comment]
Merged https://github.com/assistify/Rocket.Chat/pull/130
