### ISSUE TITLE
Custom user status

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#110]
Requested by customer:

Adding more status options than Online, Away, Offline, Invisible. In comparison to Slack, RocketChat just offers some basic status options. The customer requests the ability to add status codes on their own. 

I found an open RocketChat issue after a quick search. However this is not addressed yet:
https://github.com/RocketChat/Rocket.Chat/issues/7310

**Comment by oinadmin** [comment]
+1

**Comment by janrudolph** [comment]
Implemented.
