### ISSUE TITLE
Message that indicates a closed request room

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#116]
When closing a request room, the experts are removed and the "Chat beenden" button disappears. Just the creator of the request room stays in the room. If an expert has closed the room, the creator is not notified by this event. Thereby it is possible, that the creator does not have a clue, that all experts had left the channel. 

Therefore we need any form of notification, that the channel is now closed. Possible solutions might be:
- Write a message in the channel "channel closed"
- Replace the "Chat beenden" by a message "channel closed"

**Comment by janrudolph** [comment]
The message should also indicate why we close rooms and what happens (or not happens) when you write messages in a closed room. This might not be clear to users.

**Comment by mrsimpson** [comment]
I'd even prefer to have an explanatory text on the dialog which is shown on closing the request. Both messages, prior to closing and the generated message afterwards should be quite similar.

**Comment by mrsimpson** [comment]
Fixed with f18a657e3ae98135179b12753e8fbd689d733511
