### ISSUE TITLE
[Proxy] [Bug - Livechat] Missing sidebar tab "old conversations"

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#123]
Reported by client.

https://github.com/RocketChat/Rocket.Chat/issues/8703

**Comment by mrsimpson** [comment]
@janrudolph see https://github.com/RocketChat/Rocket.Chat/issues/8703 . Please propagate to the client

**Comment by mrsimpson** [comment]
Fixed with 54633e86dd661598704bf302aa323d9d3891ae3d
