### ISSUE TITLE
Finding old request rooms

### ISSUE THREAD

**Issue by mrsimpson** [assistify/Rocket.Chat#13]
_From @janrudolph on September 8, 2017 8:16_

As user I like to find an old request channeI, that I joined in the past, by the integrated Rocket.Chat channel search.

_Copied from original issue: mrsimpson/Rocket.Chat#90_

**Comment by mrsimpson** [comment]
@janrudolph with "the channel search", you mean the box in the left-hand-side which finds by name, right?

**Comment by mrsimpson** [comment]
at least it should appear there as well. An explicit search for requests and expertises should be possible as well

**Comment by mrsimpson** [comment]
Fixed with https://github.com/assistify/Rocket.Chat/commit/ae7407abfd5a487a952dbaa1714434371611efb0 . However, one still needs to know the room name. Tagging a room shall be part of Rocket.Chat Core. A separate request shall be opened for this feature

**Comment by ruKurz** [comment]
Great to see our CI is working - at least for our chat ;-)

**Comment by janrudolph** [comment]
I guess  we need a full text search in the end...

**Comment by ruKurz** [comment]
https://github.com/redlink-gmbh/smarti/issues/62
