### ISSUE TITLE
Inconsequent naming of private groups and channels

### ISSUE THREAD

**Issue by mrsimpson** [assistify/Rocket.Chat#132]
German translation of private groups and channels as well as their usage is not concise: 

> Wenn ich einen **Kanal** privat stelle, so ist er auf einmal eine **Gruppe**. Ist man in noch keine privaten **Gruppe**, so sagt der Text darunter sogar "Sie sind bisher kein Mitglied eines **Kanals**". Meine Anfrage wäre, eine einheitliche Namensgebung für private Kanäle zu finden, da es manche Nutzer auf den ersten Metern doch sehr verwirren kann

**Comment by jschirrmacher** [comment]
German translation was changed to `bisher nirgendwo dabei` in the meantime, so I close this issue now.
