### ISSUE TITLE
There is a misleading translation, when there is no topic created

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#133]
<img width="263" alt="bildschirmfoto 2017-11-02 um 09 30 32" src="https://user-images.githubusercontent.com/853776/32316449-8c2c023c-bfb0-11e7-8cf2-d32bc97ddc11.png">

"Sie sind bisher kein Mitglied eines Kanals"

should named

"Sie haben noch keine Anfrage angelegt"

**Comment by mrsimpson** [comment]
See #132

**Comment by mrsimpson** [comment]
Since the text for the requests is displayed to both, expert and requester, I chose "Keine Anfragen bisher"

**Comment by ruKurz** [comment]
@mrsimpson this has been a real user feedback from one of our clients.
And if the title is "Anfragen" the explaining text should fit the wording,
WDYT
