### ISSUE TITLE
[Bug] Despite viewing permissions, a user cannot view other topics

### ISSUE THREAD

**Issue by mrsimpson** [assistify/Rocket.Chat#135]
Although `view-e-room` is assigned to a user, he can find but not enter topics.

**Comment by janrudolph** [comment]
@mrsimpson is this bug not yet addressed?

**Comment by janrudolph** [comment]
obsolete if we solve https://github.com/assistify/Rocket.Chat/issues/337

**Comment by jschirrmacher** [comment]
#337 is already closed due to the new thread structure, so I close this Issue as well.
