### ISSUE TITLE
Pass topic as parameter when creating a request

### ISSUE THREAD

**Issue by mrsimpson** [assistify/Rocket.Chat#156]
# Purpose
As a user who integrates Assistify into an external tool, I want to be able to pass the topic for which a request shall be created

# Implementation
Pre-fill the request-creation with a topic passed as query parameter
`create-channel?topic=demo%20topic`

**Comment by mrsimpson** [comment]
![prefill-topic](https://user-images.githubusercontent.com/17176678/33370664-85aa3818-d4f8-11e7-8edf-07c8397d7b59.gif)

**Comment by ruKurz** [comment]
Created a confluence macro:
<img width="426" alt="bildschirmfoto 2017-11-29 um 20 53 01" src="https://user-images.githubusercontent.com/853776/33395991-81038fb8-d547-11e7-9af7-96f496ece116.png">
