### ISSUE TITLE
Chat Room name should be changed to expert area name in terms of SAP Context

### ISSUE THREAD

**Issue by mrsimpson** [assistify/Rocket.Chat#16]
_From @mrsimpson on August 8, 2017 9:48_

On the Rocket.Chat-side, the interface looks as if it already supports providing an "external expertise name": [@see createRequest](https://github.com/mrsimpson/Rocket.Chat/blob/master/packages/assistify-help-request/server/methods/createRequest.js#L43-L51)

What's missing there however is that the externally provided experts are added to the channel.

_Copied from original issue: mrsimpson/Rocket.Chat#66_

**Comment by mrsimpson** [comment]
This involves a change of the signature and thus, a change of all consumers => needs to be adapted in a compatible way, else the SAP system will not be able to create new requests until the consumption is adapted as well

**Comment by janrudolph** [comment]
pretty old => closed
