### ISSUE TITLE
When removing all experts from a request-room, they are latter added again

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#161]

**Comment by mrsimpson** [comment]
Analyzed: this happens once hiding the room but not switching to another one.
Once the existing room is re-opened (e. g. page refresh, closing and re-opening Rocket.Chat+), the subscription is getting renewed. 

Imho, hiding or leaving a room should switch away from it.

**Comment by jschirrmacher** [comment]
Should not happen any more. Closing issue.
