### ISSUE TITLE
Clarify the functionality and semantics for "leave room" and "hide room"

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#163]
**User perspective**
Independent from several reasons why both options "leave room" and "hide room" do exist, a regular user wants to quit participating that specific conversation. "Hide room" implies that the room just disappears and can be reopened again, while "leave room" means that one does really quit that conversation. IMHO the option "hide room" is superfluous. Personally I make a decision: participate or not. 

Independent there is at least one bug: Leaving a request/room as last member leads to an hidden room that re-appears after re-login (even selecting another room, to prevent the URL is recalled, after login).

**Steps to reproduce**
- Leave the request
- Open another channel
- Quit the App/logoff
- Login again
- The request is there again

**Wrong behavior**
- By leaving the request as last member there pops up an message that one can not leave a room without assigning a new owner
- After confirming that dialog, another one appears, saying that the room has been hidden.
- The room is not shown anymore in the list
- Even one enter another room before logoff from RC in order to prevent that the URL is reopened after the next login, the request room pops up again after re-login.

**Note**
- Instead of leaving the room, using the "hide room" option works. But only if selecting another room before logout and re-login

**Comment by jschirrmacher** [comment]
I cannot reproduce this behaviour any more. After confirming the first dialog, no second one appears. If I assign a new owner for the room and leave, the room stays invisible for me, even after re-login.
