### ISSUE TITLE
Search for closed requests

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#167]
## Purpose
As a user who has either given or received advice, I want to be able to look up the solution after the request has been closed.

Since I cannot find it in my active subscriptions and since the search for channels does not include the messages' content, I am kind of lost here.

## Implementation
Add the [chatpal package](https://github.com/redlink-gmbh/chatpal-search) to Assistify Rocket.Chat

**Comment by mrsimpson** [comment]
#172 has been created as duplicate. As the latter one is referenced in a PR, closing this one
