### ISSUE TITLE
Adding a description for "Hilfe beenden"

### ISSUE THREAD

**Issue by mrsimpson** [assistify/Rocket.Chat#17]
_From @janrudolph on July 5, 2017 14:48_

A description for the button "Hilfe beenden" is necessary. The description should state that a satisfied user should close the channel. Thereby the AI will learn and will provide better result next time.

_Copied from original issue: mrsimpson/Rocket.Chat#37_

**Comment by mrsimpson** [comment]
This is basically a very minor enhancement: As we own the panel ourselves, add a text (either as alt-text or as plain text below the button)

**Comment by janrudolph** [comment]
We redesigned the sidebar. This was not addressed by the redesign and I think it is not relevant anymore.
