### ISSUE TITLE
Adding a topic to a channel causes strange channel headline 

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#171]
I found a strange representation of a channel headline (name, topic), see screenshot. When removing the topic, the headline is fine.

![channel-headline](https://user-images.githubusercontent.com/3596824/33819492-069beaec-de4b-11e7-82c9-6797ae299386.png)

**Comment by janrudolph** [comment]
Issue is just present in the team chat. => @mrsimpson Have you edited the custom css?

**Comment by janrudolph** [comment]
It is quite strange. In the team chat, the topic is placed in a paragraph. In all other teams there is no paragraph. This paragraph might produce the line break.

Team Chat:

```
<span class="room-topic">
<p>Mein Thema</p>
</span>
```

Other Chats:

`<span class="room-topic">Mein Thema</span>`

**Comment by mrsimpson** [comment]
Identified this as side-effect of configuring "Marked" as markdown parser. Should be reported to RC core
