### ISSUE TITLE
Adding chatpal-search package

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#172]
https://github.com/redlink-gmbh/chatpal-search

using: as search endpiont
http://localhost:8080/rocket/localhost/search-message

**Comment by mrsimpson** [comment]
Open issues from a functional point of view

- [ ] Results from requests should by anonymized
- [ ] There should be some indication that when searching, only requests are searched. Maybe even placing it in the main window is not a good idea

**Comment by mrsimpson** [comment]
@westei How does Chatpal in Smarti handle request rooms?

**Comment by westei** [comment]
not sure if I understand correctly, but

* Chatpal:  enforces the permission; The last I know is that only rooms the user has joined are searched (but that might have changed in the meantime or is maybe configureable)
* The Smarti Konowledge base is not accessible to Chatpal. So Chatpal will never show a result from Smarti.

**Comment by mrsimpson** [comment]
I consider this closed: Chatpal-Search has been aded. It has a different scope compared to smarti and taht's fine. We might create a new issue about also searching anonymized conversations of the team from Smarti via Chatpal
