### ISSUE TITLE
Add more lines to question field

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#176]
The height of the question-field is not appropriate. If a user writes a long question, the user is not able to read the whole text. We should add some textarea lines.

<img width="372" alt="question-input-field" src="https://user-images.githubusercontent.com/3596824/34029234-adc737e4-e167-11e7-91f5-4f7fda9b456a.png">

**Comment by mrsimpson** [comment]
This should scale automatically, like the message input

**Comment by janrudolph** [comment]
Hm, i would prefer to have 2-3 lines as default. Personally I think that just one line narrows your thoughts.

**Comment by mrsimpson** [comment]
@vickyokrm can you please take over? I believe rows=„3“ should be fine. If you could figure out what to do for the resizing, this was beautiful

**Comment by mrsimpson** [comment]
Detected issues

* The Enter-key does not send the message on the creation screen anymore
* Enter in the standard message box makes it bounce instead of sending
* Sometimes (unreproducible), the standard message input has a higher height when nothing has been entered.
