### ISSUE TITLE
Make people ask questions - the question-guidance-bot

### ISSUE THREAD

**Issue by mrsimpson** [assistify/Rocket.Chat#178]
## Motivation
We want to make people ask questions in an isolated room - since only this makes knowledge re-useable.

## Current situation
Currently, Assistify only offers one way of asking a question: creating a request via the create-room-dialog. This does not only have a second-class user experience, it also relies on the user knowing (and appreciating) the different room types.
The barrier is quite high for casual users - we need to educate them.

## Proposal
A how-to-ask-questions-chatbot shall facilitate the process of guiding a user.
- Identify if a question has been asked
- Ask the user whether he wants to create a new question room - optionally also explain why this is a good idea
- Invite the proper users (experts) into this new question-room
- Ideally help the user to formulate the question if he has trouble doing that on his own
- Identify once a question has been solved and make the user close the question

## Dependencies
- Belongs to #177 
- relies on https://github.com/RocketChat/Rocket.Chat/issues/9177 to be implemented in RC core

**Comment by janrudolph** [comment]
One big assumption here: learning ist just possible if communication happens in an isolated room. We never have verified this, have we?

In general, I highly agree with the content. The challenging point is the user interface. There are several options for guidance:
- a bot as outlined (a conversational interface) which might be annoying if it appears everytime a question is raised
- a button „ask a question“ which appears when a question is detected (or that is always present) and then opens the request creation form. This is a less interactive solution 

I like the idea of an assistant which helps me to find answers and experts. However I am concerned about the UX (when the user does not like to get help)
