### ISSUE TITLE
Turn the request-room-type into a more generic "question"

### ISSUE THREAD

**Issue by mrsimpson** [assistify/Rocket.Chat#179]
## Motivation

Currently, requests are the heavy threads based on topics only.
This limits their usage and requires casual users to understand the data model and room types. In order to allow more flexible processes for asking a question (#145, #178), the request must not only be created on the basis of a topic but also on any public or private channel.

## Purpose

The question shall have a very similar semantic like the request: It shall serve as the room for a coherent discussion in order to get an answer to a question. It shall have a defined end and AI (Smarti) shall try help to get the question solved.

## Proposal

- Rename the "request" to "question"
- Migrate all the current requests (rooms, subscriptions, permissions)
- Rename all references
- Don't only store the topic's name as a reference, but use a parent room id if available
- It shall still be possible to create a questions without having a parent room inside Rocket.Chat in order to allow the area of knowledge to be defined in a remote system
- Topics are still one parent for which questions are created - without the need of joining a topic
- Adapt the navigation bar so that it can group questions based on parent rooms (simlar as done in Zulip). This makes an unred-counter necessary or some other visualization to point the user to new messages in questions
![image](https://user-images.githubusercontent.com/17176678/34148302-1125a60e-e4a1-11e7-9156-c23bf4d4072b.png)

This will lead to heavyweight threading in Rocket.Chat. Ideally, the package including the questions is isolated so that it could be contributed.

## Dependencies
- Addresses #177

**Comment by janrudolph** [comment]
Why do we need a hirarchy? Is it not enough to introduce „tags“ for a question? Any user can define tags when the user creates a new question. Smarti will help and suggest tags that might fit to the new question - based on old tags (= a cup of magic). Experts can follow tags. By adding more than one tag, the „hirarchy“ is more flexible and meshed. Sure, there will be inconsistencies, but, as social media shows, tags are highly accepted for structuring information.

**Comment by mrsimpson** [comment]
with respect to grouping in nav bar, see https://github.com/RocketChat/Rocket.Chat/pull/8873

**Comment by mrsimpson** [comment]
@janrudolph I believe we should have a hierarchy since a question has spun off a particular message - and there naturally is some kind of hierarchy.
To have tags **in addition**  and as some way to follow particular rooms is a good idea though. This is also related #41. Wdyt about opening another issue for the tagging and its implications?

**Comment by janrudolph** [comment]
@mrsimpson Okay, let‘s open a new issue about the tags.

**Comment by mrsimpson** [comment]
closed since #418 follows up with some changed features
