### ISSUE TITLE
Counting of request channels is not user friendly 

### ISSUE THREAD

**Issue by mrsimpson** [assistify/Rocket.Chat#18]
_From @janrudolph on July 12, 2017 8:51_

**Current Situation**
Every new request gets an unique id, consisting of the topic name and a global request count. 

**Issue**
From a user perspective, it is not favorable to have a channel name which contains a global count. This might be confusing for the user or even the admin. 

**Example**
Let's consider there a two topics. There are no requests concerning topic A. In the past, three requests were created regarding topic B. Now, an user creates the first request for topic A. This new topic will get the title "<topic A name> - 4" instead of "<topic A name> - 1"

**Possible Solution**
Adding counts on topic level.

_Copied from original issue: mrsimpson/Rocket.Chat#39_

**Comment by ruKurz** [comment]
Are LiveChats included by this issue?

**Comment by janrudolph** [comment]
@mrsimpson We have the new creation dialogue with the title attribute. I guess we can close this issue, since the new dialogue allows adding meaningful titles.
