### ISSUE TITLE
[Proxy] [Bug] App does not show Bot messages #1167

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#194]
### Description:

When closing a request, a bot posts a message into the channel.

### Client Information:

* iOS App Rocket.Chat+ 1.8.0

### Steps to Reproduce:

1. Open a request
2. Write something
3. Close the request

### Expected behavior:

Bot posts an info message. This message can be seen on any device.

### Actual behavior:

In the Rocket.Chat+ App the Bot message is not displayed.

![bot-closing-comment-mobile](https://user-images.githubusercontent.com/3596824/34930643-ca67f6f6-f9ca-11e7-9be1-6865c556db76.jpg)

**Comment by mrsimpson** [comment]
This is a custom message type created by the standard RC API. Please create the issue for the display on the RocketChat+ Repository. Note that if this occurs also on Android, two issues need to be created

**Comment by janrudolph** [comment]
I reopen this issue in order to track the new one:

https://github.com/RocketChat/Rocket.Chat.iOS/issues/1167
