### ISSUE TITLE
Guests cannot create new requests

### ISSUE THREAD

**Issue by mrsimpson** [assistify/Rocket.Chat#197]
# Motivation
As a guest, I want to be able to open a new request

# Issue
The +-Icon for creating a new room is not available
![gast eingeschrankte sicht](https://user-images.githubusercontent.com/17176678/35037646-720950ea-fb78-11e7-8523-59a3809ea6b4.png)

**Comment by janrudolph** [comment]
Why should a guest open requests, especially for team-internal topics? There might be "open" topics but we have not implemented a permission system for topics.

**Comment by mrsimpson** [comment]
Not a very high priority, but still nasty: a team can have Assistify as incoming (support) channel for its developers. While via live chat, guests can interact with the team, guest via self-registration can not issue new matters. This will result in a lot of clutter in the welcome-channels, I suppose

**Comment by janrudolph** [comment]
PR https://github.com/assistify/Rocket.Chat/pull/275
