### ISSUE TITLE
Notification for new requests of a specific topic

### ISSUE THREAD

**Issue by andytipp** [assistify/Rocket.Chat#198]
As an admin user, I want to create an outgoing integration that sends a notification to another rocket chat entity when a new request for a specific topic (i.e. "Assistify") is opened. 

There already is a way to notify for all public channels, all private groups or all direct messages, as can be seen in the attached screenshot

![outgoing integration](https://user-images.githubusercontent.com/23705040/35214059-2b2dfce8-ff60-11e7-9ba3-c6e3c667cc82.png)

**Comment by janrudolph** [comment]
Already done
