### ISSUE TITLE
Use S3 as storage provider for all teams

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#199]
Rocket.Chat enables teams to use S3 as storage provider. We like to use this feature in order to store all files of a team. However, we have to store the data of different teams in one single bucket. Since the data should not be messed up, we have to establish a folder structure.

**Acceptance criteria:**
- Store uploaded data in a defined folder within a S3 bucket
- Add option to define a folder within a bucket as storage location. If the admin does not define a folder, the data is stored in the top-level directory. 
- Tests are available.

@mrsimpson Please review.

**Comment by mrsimpson** [comment]
Talked to @geekgonecrazy y‘day evening. As per what I understood this is already state of the implementation. We need to verify it though

**Comment by janrudolph** [comment]
Even better...

**Comment by janrudolph** [comment]
done
