### ISSUE TITLE
Provide compact request creation form

### ISSUE THREAD

**Issue by mrsimpson** [assistify/Rocket.Chat#20]
It shall be possible to create a request for a particular topic with a minimal UI, so that the URL of this component can be easily integrated into existing HTML-pages via iFrame.
Thie feature shall be provided from within Rocket.Chat (no external consumption of RC APIs), so that all authentication, routing etc. is handled by Rocket.Chat.
Thus, this includes the need to provide a compact version of the login-form.

**Comment by mrsimpson** [comment]
https://github.com/assistify/Rocket.Chat/blob/15a18a8454fdda973a55cede97d15b42d30c8f80/packages/rocketchat-ui-login/client/login/layout.html#L2 this is where a custom parameter could be interpreted in order to load a custom CSS for the minified login.

**Comment by janrudolph** [comment]
Integration Example "Wiki page":

![wiki-page](https://user-images.githubusercontent.com/3596824/30847025-4378b19e-a29a-11e7-8581-340430e91e5f.jpg)
