### ISSUE TITLE
[Proxy] Setting colors by API does not work anymore #9628

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#207]
https://github.com/RocketChat/Rocket.Chat/issues/9628

**Comment by ThomasRoehl** [comment]
There are two solutions I can think about:
1. we change the api endpoint in order to set the type to color
something like:
```
check(this.bodyParams, {
			value: Match.Any
                         editor: 'expression | color'
		});
```
2. change the default to color
