### ISSUE TITLE
Enable guest users to create requests

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#209]
# Motivation
We want to make more use of the request mode. Currently, only registered users in a team can use Question Mode. To allow any user to ask questions to any Assistify team, the guest role should be allowed to create new questions.

This would result in the possibility that, e. g. from a confluence or from Koyo, requests can be sent to a team via web form.

**Comment by janrudolph** [comment]
https://github.com/assistify/Rocket.Chat/pull/275
