### ISSUE TITLE
Alternative UI for live chat

### ISSUE THREAD

**Issue by mrsimpson** [assistify/Rocket.Chat#21]
#Functional description 
Live chat currently only exists as widget.
In some cases, there exists no webpage which can be used to attach the widget to.
In these cases, it was beneficial if there was a particular component in the Rocket.Chat live-chat, which provides a stand-alone access to live-chat-features.

# Acceptance criteria

* Route on the RC server leading to a live-chat-application
* Ability to register as guest
* options to write messages and end the chat
* PR to Rocket.Chat opened without Travis issues

**Comment by janrudolph** [comment]
pretty old => close. if necessary, please reopen.
