### ISSUE TITLE
Adjust "config-expert" permissions

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#211]
Please edit the "config-expert" permission set by applying the following list:

Remove:

- General → Translations (all settings)
- General → UTF-8 (all settings)
- E-Mail (all settings)
- Accounts → Iframe (all settings)
- Accounts_BlockedDomainsList
- Message → Markdown (all settings)
- Message → Message_MaxAllowedSize
- Message → API_EmbedIgnoredHosts

Add:

- Accounts_RegistrationForm
- Accounts_RegistrationForm_SecretURL
- Accounts_RegistrationForm_LinkReplacementText
- Accounts_Registration_AuthenticationServices_Enabled
- Accounts_Registration_AuthenticationServices_Default_Roles

**Comment by andytipp** [comment]
Please also add the permission "manage-assets" to the permission set so that config-experts can change their assets (e.g. favicon and logo).

**Comment by ruKurz** [comment]
@janrudolph which permissions do you mean by "E-Mail (all settings)"?

```
		'change-setting-Verification_Email',
		'change-setting-Verification_Email_Subject',
		'change-setting-Verification_Customized',
		'change-setting-Forgot_Password_Email',
		'change-setting-Forgot_Password_Email_Subject',
		'change-setting-Forgot_Password_Customized',
		'change-setting-Accounts_UserAddedEmail',
		'change-setting-Accounts_UserAddedEmailSubject',
		'change-setting-Accounts_UserAddedEmail_Customized',
		'change-setting-Accounts_Enrollment_Email',
		'change-setting-Accounts_Enrollment_Email_Subject',
		'change-setting-Accounts_Enrollment_Customized',
		'change-setting-Invitation_HTML',
		'change-setting-Invitation_Subject',
		'change-setting-Invitation_Customized',
		'change-setting-Email_Footer',
		'change-setting-Email_Header',
		'change-setting-Offline_Mention_All_Email',
		'change-setting-Offline_Mention_Email',
		'change-setting-Email',
```

**Comment by ruKurz** [comment]
@andytipp I checked the current permission set. The `config-expert` is able to change the following permissions:

```
		'change-setting-Assets_safari_pinned',
		'change-setting-Assets_tile_310_wide',
		'change-setting-Assets_tile_310_square',
		'change-setting-Assets_tile_150',
		'change-setting-Assets_tile_144',
		'change-setting-Assets_touchicon_180_pre',
		'change-setting-Assets_touchicon_180',
		'change-setting-Assets_favicon_512',
		'change-setting-Assets_favicon_192',
		'change-setting-Assets_favicon_32',
		'change-setting-Assets_favicon_16',
		'change-setting-Assets_favicon',
		'change-setting-Assets_favicon_ico',
		'change-setting-Assets_logo',
		'change-setting-Assets_SvgFavicon_Enable',
		'change-setting-Assets',
```

@see https://github.com/assistify/Rocket.Chat/blob/develop/packages/assistify-defaults/server/roles.js#L91
an following.
