### ISSUE TITLE
Add title and first message to new request

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#23]
As user I want to add a title when creating a new request in order to get a better overview in my request list.

Acceptance criteria:
- When an user creates a request, the user has to select a topic and to specify a title.
- The title is a string (about 50 chars long, HTML input field).
- The title becomes part of the channel name. The new channel name will be "[topic name] - [title]".

**Comment by mrsimpson** [comment]
@janrudolph How shall the user be asked for entering a title - and where?

**Comment by janrudolph** [comment]
What do you think about this solution:

![rocket_chat_](https://user-images.githubusercontent.com/3596824/30809107-e8615bf6-a200-11e7-8987-3ce35e27eadc.png)

**Comment by mrsimpson** [comment]
This will change with the next generation UI-design. But the general idea is understood.
In addition to entering it, it should be used in the navigation, I guess. Making the title be displayed instead of the name should be a per-user-preference, I guess.
This part should also be contributed to RC then

**Comment by janrudolph** [comment]
Yeah, it should be used in the navigation, because you pick a channel there (and you like to know which channel you pick).

**Comment by mrsimpson** [comment]
so we do have actually two separate tasks: 

1. Improve the UI in the left hand side nav-bar with an input of the title and copy it to the field labelled "Thema" in your screenshot.
2. Implement a user-preference to switch whether the title of the name of the room shall be displayed in the nav bar

**Comment by mrsimpson** [comment]
As we've got much more space on the creation page, kindly add the first message optionally as well

**Comment by mrsimpson** [comment]
@vickyokrm 

see 

- `packages/assistify-help-request/server/methods/createRequest.js`
- for error handling on the UI `packages/rocketchat-ui/client/views/app/createChannel.html`

**Comment by janrudolph** [comment]
One small improvement: The height of the question-field  is not appropriate. If a user writes a long question, the user is not able to read the whole text. We should add some textarea lines.

@mrsimpson @vickyokrm However, this issue is done, right?

**Comment by vickyokrm** [comment]
@janrudolph Okay. Shall we track the minor improvement as a bug and set this issue to completed ?

**Comment by janrudolph** [comment]
@vickyokrm Yes, lets do it that way. I will add the issue. You can close this one.
