### ISSUE TITLE
[Proxy] Channel name differs between channel headline and info panel #9738

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#239]
https://github.com/RocketChat/Rocket.Chat/issues/9738

**Comment by vickyokrm** [comment]
@janrudolph The new settings layout->use real names should be used to show/hide display name and the changes required on the assistify side has been taken care. There is the pull request pending review which will resolve this issue. [PR: 244 here](https://github.com/assistify/Rocket.Chat/pull/244)
