### ISSUE TITLE
[Proxy] On/off Buttons - Where does the blue border come from 

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#242]
<img width="191" alt="rocket_chat_" src="https://user-images.githubusercontent.com/3596824/36303461-80277d2c-130c-11e8-9e6c-dfa68aaf4bc6.png">

I have not found the CSS / Color specification for the `blue` border. Does anyone has a clue?

**Comment by ThomasRoehl** [comment]
The original Color is also blue, so it might be hard-coded:
![image](https://user-images.githubusercontent.com/11913979/37095622-bbb67c4e-2216-11e8-8de1-5bc874453bbe.png)

**Comment by janrudolph** [comment]
Moved: https://github.com/RocketChat/Rocket.Chat/issues/10057

**Comment by janrudolph** [comment]
Closed via https://github.com/RocketChat/Rocket.Chat/pull/10081
