### ISSUE TITLE
Guest user can access the create channel dialog, but can't create any channel: No error message shown

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#248]
### Actual behavior

When a guest user opens the create dialog he is able to access the create channel dialog. After he finished the form and tries to create the channel, the dialog does not close or show any error. It just does nothing.

### Expected behavior

The guest user should not be able to open the create channel dialog at all.

**Comment by janrudolph** [comment]
PR https://github.com/assistify/Rocket.Chat/pull/275
