### ISSUE TITLE
[Bug] Knowledge base is not available in livechat

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#262]
### Description:

The knowledge base is not available in livechat since Smarti 0.7

### Server Setup Information:

* Version of Rocket.Chat Server: 0.61

### Steps to Reproduce:

1. Create a new livechat conversation by using the widget
2. Open new conversation in the backend
3. Open knowledge base
4. Knowledge base will not load

### Expected behavior:

Knowledge base will show any results.

### Actual behavior:

Knowledge base is loading....

<img width="199" alt="_ __db_mobilitatsservicezentrale_by_assistify_und_rocket_chat_" src="https://user-images.githubusercontent.com/3596824/36893316-ddcbf772-1e07-11e8-99bc-1edd944b705f.png">

For requests everything works fine.

@mrsimpson @ThomasRoehl May you please have a look on this issue?

**Comment by mrsimpson** [comment]
it's an error in the livechat-adapter.

**Comment by janrudolph** [comment]
fixed by https://github.com/assistify/Rocket.Chat/pull/265 thank you very much @mrsimpson !
