### ISSUE TITLE
[Proxy] [Bug] Guests do not see channels in the left sidebar #9974

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#263]
https://github.com/RocketChat/Rocket.Chat/issues/9974

**Comment by ThomasRoehl** [comment]
@janrudolph we need to enable the permission: `View Private Room [view-p-room]` for guests.
Tested on our develop branch.
After the permission is enabled for guests, they can see private channels in the sidebar as well.

Can you verify that?
