### ISSUE TITLE
Notify the user when his request has not been closed in a while

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#289]
**General idea:**
We like to have coherent conversations and need to know when a question is solved. Because of this we ask users to close requests. However, some users do not close conversations. To motivate we should push users to close conversations. Nice side effect: Users will get a cleaner UI if they close chats. The open chats will not clutter the left sidebar.

**Proposed solution**
Notify the user when a request has not been closed in a while. The bot may ask the user if the question has been answered and if the user likes to close the request. 

_Acceptance criteria:_
- After a certain time of inactivity in a request channel, a bot sends a message to the questioner (@-annotation) in the request channel. The bot asks the questioner if the question is solved. Example message: 
`"Hey @joe, is your question solved? If yes, please [close](LINK to close) the conversation. If not, maybe ask @all to help you making progress"`
- Admins are able to configure the period until the bot interferes.
- The bot randomly choses between different messages (which have the same meaning). By this it gets more natural and less boring. 

In the future a bot like this could also ask to rate the solution, or to indicate the messages which helped the user.

**Comment by mrsimpson** [comment]
Remind-me-alike feature.
There are various ways to implement that:

- Hook after send message, function with timer
- Engage external engine after send message
