### ISSUE TITLE
Shortening long URLs

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#29]
**Current state**
When entering a long URL in the chat, Assistify always shows the full path.

**Preferred state**
When the length of the URL the user enters is bigger than a certain length, Assistify only shows a smaller part of the URL.

Originally by @andytipp https://github.com/mrsimpson/Rocket.Chat/issues/72

**Comment by ruKurz** [comment]
@vickyokrm is this the issue you're currently working on?
