### ISSUE TITLE
Anfrage an einen Kanal senden

### ISSUE THREAD

**Issue by mulatli** [assistify/Rocket.Chat#295]
Sehr geehrte Damen und Herren,

ich bin Assistify user und als User wünsche ich mir, dass ich eine Möglichkeit hätte eine Anfrage auf Freischaltung zu einem Canal schicken zu können. Zur Zeit, kann ich mich irren, gibt es solche Funktionalität nicht. Ich muss erst den/die Canal Owner/in per Tel., Email, persönlich usw. nach fragen, ob er/sie mich freischalten kann. Manchmal sind diese Owners vergeßlich und ich muss die Anfrage oft wiederholen bis ich freigeschaltet werde ;-)(. Wie sehen Sie das?

Mit freundlichen Grüßen
Zamy Getachew

**Comment by mrsimpson** [comment]
Hi Zamy, 
Du stellst Di das dann so vor, dass man private Gruppen finden kann, aber keinen Inhalt sieht. Stattdessen soll man einen Button haben, um eine "Anfrage auf Einladung" an den Owner des Channels zu senden, richtig?
