### ISSUE TITLE
A guest that is member of a closed channel does not see the cannel in the sidebar

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#299]
<img width="1046" alt="bildschirmfoto_2018-03-28_um_20_50_42" src="https://user-images.githubusercontent.com/853776/38050184-78f65266-32ca-11e8-88de-20b657854a99.png">

**Comment by janrudolph** [comment]
Duplicate to https://github.com/assistify/Rocket.Chat/issues/263
