### ISSUE TITLE
Canceling the termination of a conversation does not work

### ISSUE THREAD

**Issue by mrsimpson** [assistify/Rocket.Chat#3]
_From @janrudolph on August 14, 2017 7:27_

A conversation is finished (livechat, request). The user likes to terminate the conversation. But the user realizes that there is an additional question. Therefore the user cancels the termination dialog.

**Issue**
It is not possible to cancel the termination dialog. The conversation is closed when pressing the button "Hilfe beenden".

**Solution**
Terminate conversation when user confirms the popup.

_Copied from original issue: mrsimpson/Rocket.Chat#70_

**Comment by mrsimpson** [comment]
_From @ruKurz on September 11, 2017 7:48_

Is this a custom issue or is this a general rocket.chat issue?

**Comment by mrsimpson** [comment]
@ruKurz this is an issue of our custom closing dialog. The full sidebar including actions is provided by us.

**Comment by ruKurz** [comment]
OK, thanks for your reply. Since you have moved this issue, the answer was implicit given so I deleted my initial comment. Anyway thanks.

**Comment by mrsimpson** [comment]
fixed with #4
