### ISSUE TITLE
Indicate topic-request relationship in channel list

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#305]
_As an user I want to know at a glance to which topic a question belongs so that I get a fast and easy overview._

**Acceptance criteria:**
- Group questions (= requests) of the same topic in the left sidebar, either by using the same channel picture or by displaying a hierarchy as suggested in https://github.com/assistify/Rocket.Chat/issues/179

**Current situation:**
<img width="160" alt="request-topics-assistify" src="https://user-images.githubusercontent.com/3596824/38407001-18a685b6-3978-11e8-988d-73373defecf8.png">

**Comment by mrsimpson** [comment]
This is a result of the was we implement threading.
Introducing a hierarchy will result in much different experiences on mobile and browser. Also, it is really heavy to implement

## Proposal

Chose the symbol (and color) of requests based on the topic (the topic which can be modified by the user in the room properties). 
In the course of this, also make sure that the topic is always properly populated. For threads out of requests, the topic should be copied from the (top level) expertise.
