### ISSUE TITLE
Add new users with @-annotation

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#306]
As user I want to add other users to a channel by simply mentioning their names. This is a more convenient way to add users. I do not want to use a slash command or use the member list to add new users. This way should not apply for direct messages.

**Comment by mrsimpson** [comment]
Adding a user simply by mentioning is not a common behavior for any room type. Thus, implementing this for requests is kind-of special and can create additional confusion. 

The slash-command and the invite-button is possible. => minor priority

**Comment by janrudolph** [comment]
lets skip this. It is not important and has implications on general RocketChat behavior
