### ISSUE TITLE
Editing the very first message of a thread does not bring the message text into the chat input field.

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#310]
### Description:

When starting a new thread beginning from a single message, the text of this message is brought into the new sub channel. The text of this very first message can't be edited.

### Steps to Reproduce:

1. Start a thread
2. edit the first message
3. the message text comes not into the chat input field

### Expected behavior:

When editing the first message of a thread the text should be overtaken into the chat input field. 

### Actual behavior:

The text is not overtaken into the the chat input field.

**Comment by mrsimpson** [comment]
Seems to be fixed in 0.63.

Arrow-up-shortcut doesn't work, but that's kind-of-intentional
