### ISSUE TITLE
Topic is not copied from the parent expertise

### ISSUE THREAD

**Issue by mrsimpson** [assistify/Rocket.Chat#316]
![image](https://user-images.githubusercontent.com/17176678/38922643-f3ba5072-42f8-11e8-9b65-006834c26cc3.png)

Neither when creating a thread not when using the creation dialog, this is properly populated

**Comment by vickyokrm** [comment]
@mrsimpson  I believe issue was already fixed. Does the issue still persists?

**Comment by mrsimpson** [comment]
I think it still exists. Please validate.

**Comment by vickyokrm** [comment]
Tested. The topic value propagated to the request that are created from the creation dialog as well as the while threading.

**Comment by mrsimpson** [comment]
Well, the we’ll have to check how it’s propagated to Smarti. I have seen some guids as topic in the widget when threading

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
