### ISSUE TITLE
[Proxy] Validate "Site_URL" in backend #10716

### ISSUE THREAD

**Issue by steffikunze** [assistify/Rocket.Chat#329]
Your Rocket.Chat app version: 2.2.0 (159)
Your Rocket.Chat server version: 0.63.3
Device (or Simulator) you're running with: iPhone SE

You can upload the image, but only see a white field. Also the uploaded pictures of others are not displayed correctly.

![picture upload](https://user-images.githubusercontent.com/39053063/39699789-f168b744-51fa-11e8-849f-4716ac1e7a5c.PNG)

**Comment by janrudolph** [comment]
=> discussion continues here: https://github.com/RocketChat/Rocket.Chat/issues/10716
