### ISSUE TITLE
New field $loki in request in outgoing webhook script crashes integration

### ISSUE THREAD

**Issue by andytipp** [assistify/Rocket.Chat#334]
I am creating an outgoing integration that sends a notification every time users either send a message to a specific channel X. Configuring the script of this integration, I am using the JSON object `request`.

Since RocketChat 0.63.3, there is an additional field `request.data.room.'$loki' `, that has not been there in the earlier versions. Executing the integration as usual, this field apparently causes the following excepction:

```Exception in defer callback: MongoError: The dollar ($) prefixed field '$loki' in 'httpCallData.room.$loki' is not valid for storage.     at Function.MongoError.create (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/error.js:31:11)     at toError (/opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:139:22)     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/collection.js:1059:67     at /opt/Rocket.Chat/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:469:18     at _combinedTickCallback (internal/process/next_tick.js:131:7)     at process._tickDomainCallback (internal/process/next_tick.js:218:9) ```

I am using the following script in my integration: 

```
class Script {
	prepare_outgoing_request({
		request
	}) {
		if (request.data.room.t === "r" && request.data.room.expertise.toLowerCase() === "X") {
			request.data.url = request.data.siteUrl + "/request/" + request.data.room.name;
			return request;
		} else {
			return false;
		}
	}
	process_outgoing_response({
		request,
		response
	}) {}
}
```

The request object in full looks as follows:

```
{
	params: {},
	method: 'POST',
	url: 'https://myURL/hooks/4uoWTyF9sP77gY6Bq/j4eSSf38HHStfJW2P2nXPXgNFrj9iLPrEBhdF2na9YzXmor8',
	data: {
		token: '1234',
		bot: false,
		channel_id: 'fwbQKKGHshfzQwpyM',
		channel_name: 'My Channel Name',
		message_id: 'kdTHbMZuLDPAdWjAi',
		timestamp: 2018 - 05 - 18T08: 20: 54.097Z,
		user_id: 'WX8NtoAS4mYACGWxu',
		user_name: 'my_user',
		text: 'Test',
		room: {
			_id: 'fwbQKKGHshfzQwpyM',
			name: 'my-channel-name',
			fname: 'My Channel Name',
			t: 'r',
			msgs: 2,
			u: [Object],
			expertise: 'myExpertise',
			ts: 2018 - 05 - 18T08: 11: 05.945Z,
			ro: false,
			sysMes: true,
			_updatedAt: 2018 - 05 - 18T08: 11: 06.142Z,
			meta: [Object],
			'$loki': 37,
			usernames: [Array],
			topic: 'myTopic',
			helpRequestId: 'YrW4TSQrHLWrgZbGj',
			v: [Object],
			lm: 2018 - 05 - 18T08: 11: 06.127Z,
			username: 'my_user'
		},
		siteUrl: 'https://myURL'
	},
	auth: undefined,
	npmRequestOptions: {
		rejectUnauthorized: true,
		strictSSL: true
	},
	headers: {
		'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36'
	}
}
```

**Comment by janrudolph** [comment]
@mrsimpson Are there any open points regarding the integration issues? Can we close this issue?
