### ISSUE TITLE
Hide room from directory

### ISSUE THREAD

**Issue by mrsimpson** [assistify/Rocket.Chat#336]
In #319 we introduce the list of private groups. This renders all private groups, their existence and title visible. This is an incompatible change and thus, we need to protect the privacy of already.

- [x] Introduce a property to the room: "Hidden from the directory". It does not have to be restricted to private groups"
- [x] Don't list those rooms in the directory
- [x] Provide a migration which sets this property to "true" for existing private groups
- [x] For new private  groups, the property should be false

**Comment by janrudolph** [comment]
merged
