### ISSUE TITLE
Use regular channels as topics and get rid off channel type "expertise"

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#337]
We added a special room type called `expertise`. Users are able to start requests based on those `expertise` rooms. Moreover users can join `expertise` rooms in order to help others.

User feedback has revealed that `expertise` rooms compete with regular rooms. Users do not see the benefit of having `expertise` rooms. Since most teams do not use `expertise` rooms, they cannot start requests based on them. Hence they also cannot use the knowledge base so far. 

Regular rooms act as topics already. Users who are interested in the rooms topic join those. This is the same mechanism we established with `expertise` channels.

I suggest to remove `expertise` rooms and allow users to start requests based on regular channels (public/private). 

**Acceptance criteria:**
- [ ] Remove channel type `expertise`.
- [ ] Remove `#Experts` channel.
- [ ] Remove permission to add new `expertise` rooms based on membership in `#Experts`
- [ ] Allow users to create requests based on public channels.
- [ ] Allow users to create requests based on private channels they are part of.
- [ ] Allow users to create requests based on private channels they are not part of and which are not hidden(see https://github.com/assistify/Rocket.Chat/issues/336) 
- [ ]  Adjust word cloud (https://github.com/assistify/Rocket.Chat/pull/169) 
- [ ]  Provide migration script: `expertise` -> `group` (not hidden)

**Comment by mrsimpson** [comment]
Given the ability to start a question for private and public channels, the feature to be developed is to "create a thread for exery room without necessarily joining the parent room".
With this in mind, the question to be ansered is how to make the selection of the proper parent room as easy and reliable as possible.
I would differentiate two situations: 

- The user knows the parent context =>
  - start a real thread out of the parent room in which the user is already involved. Difference to today: Don't ask the question and then use the context menu to create the room, but start straight "with the thread as target in mind" => this action should not be visualized on the message context menu, but some other place
  - The user is not regularly part of this parent room's context => He browses the directory => integrate there
- The user does not know the context =>
  We have to provide a similar screen like "create request" today. For simplicity, 
  - the title could be omitted (e.g. by generating the room name based on the first sentence).
  - The parent room should be guessed by smarti (e.g. by making a MLT based on the question entered). Fallback if nothing makes good sense was the "general" channel
