### ISSUE TITLE
Nachrichten verloren

### ISSUE THREAD

**Issue by magner58** [assistify/Rocket.Chat#338]
Am 24.05.2018 gegen 11:05 wurde ich bei alle Instanzen von vendo ausgellogt und wenn ich mich wieder eingeloggt habe, könnte ich einige neue Nachrichten nicht finden.

**Comment by mrsimpson** [comment]
es handelte sich um ein Infrastrutkurproblem. Es wurden Server neu gestartet. Durch die fehlende Stickyness zu dem Zeitpunkt wurden die Sessions terminitert. Scheinbar gab es Daten, die zu diesem Zeitpunkt noch nicht ihren Weg auf die DB gefunden haben. Diese gingen leider verloren. Wir suchen nach der Ursache. 

Danke für die Meldung!

Da das (zumindest software-seitig) nicht nachvollziehbar ist, schließe ich dieses Issue
