### ISSUE TITLE
Performance issue in topics (frontend)

### ISSUE THREAD

**Issue by mrsimpson** [assistify/Rocket.Chat#341]
When opening a topic with a long history, the UI is very laggy (e. g. `#Smarti` on our team chat).
Also when writing a new message, it seems as if all displayed messages were re-rendered.
In addition to that, *all* messages of a topic channel are loaded at once. This differs from the behavior of e. g. public channels which are loaded in a lazy/paged manner.

**Comment by mrsimpson** [comment]
It seems that only after writing a message the rest of the messages is being loaded.

**Comment by ThomasRoehl** [comment]
no topics anymore
