### ISSUE TITLE
The knowledge base is not displayed in many topics and requests

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#345]
As intended, an user helped herself by using the knowledge base. However, after closing the room the knowledge base is not available anymore. Please see screenshot below. 

client = `mc`

![trotz_hilfe-raum_nicht_gefunden](https://user-images.githubusercontent.com/3596824/40957085-bbe884f0-6893-11e8-8327-4eb58b8eba8c.png)

**Comment by ruKurz** [comment]
I investigated some minutes with @ThomasRoehl to analyze the cause of this problem.
We're obeserving this behaivor not only when the knowledge base has been used: The Smarti Widget  stops working correctly when the synchronization "Chat <-> Smarti" is being triggered for an request or topic.

The browser logs an error: **No conversation found for ID: <Conversation_ID>**

A first look into the code shows that when synchronizing the Rocket.chat rooms with the knowledge base, the conversation is deleted from Smarti and then a new conversation is created in Smarti. This creates a completely new ConversationID in Smarti for the same room in Rocket.Chat.

ConversationIDs are stored in the Rocket.chat "livechatexternalmessages" collection as well as in the Smarti mapping table (for the legacy webservice). In all probability the "livechatexternalmessages" collection will not be updated when synchronizing the Rocket.chat rooms with the knowledge base. This probably means that the function "getConversationID" retrieves the obsolete ID from the "livechatexternalmessages" collection and not directly from Smarti.

Furthermore we noticed during the analysis that the action "Resync Smarti" in the Rocket.chat admin backend does not seem to trigger the complete resynch (no output in the log). Also, there seem to be problems with the labels (for the button and the description).

**Comment by ruKurz** [comment]
Here a complete new conversation is being created:
https://github.com/assistify/Rocket.Chat/blob/develop/packages/assistify-ai/server/methods/SmartiReload.js#L140

**Comment by ruKurz** [comment]
**Also compare different implementations of getConversationId**

1. SmartiAdapter.js#_getConversationId(roomId, message)
https://github.com/assistify/Rocket.Chat/blob/develop/packages/assistify-ai/server/lib/SmartiAdapter.js#L42

2. SmartiWidgetBackend.js#getConversationId(channelId)**
https://github.com/assistify/Rocket.Chat/blob/develop/packages/assistify-ai/server/methods/SmartiWidgetBackend.js#L22


Both are updating the external messages.

Update Mapping implementation:
https://github.com/assistify/Rocket.Chat/blob/develop/packages/assistify-ai/server/lib/SmartiAdapter.js#L21

**Comment by ruKurz** [comment]
@ThomasRoehl please feel free to correct my comments if they are technically not that precise.
