### ISSUE TITLE
SmartiAdapter.getConversationId should use the legacy endpoint as fallback

### ISSUE THREAD

**Issue by ThomasRoehl** [assistify/Rocket.Chat#350]
At the moment the mapping between RC rooms and Smarti conversations is done only on RC side.
We should have a backup option to get the mapping on Smarti side via the legacy endpoint:
`GET /legacy/rocket.chat`

depends on: redlink-gmbh/smarti#259

**Comment by ruKurz** [comment]
Fixed within: https://github.com/assistify/Rocket.Chat/pull/346
