### ISSUE TITLE
Reply message is autotranslated even when autotranslate is disabled

### ISSUE THREAD

**Issue by ThomasRoehl** [assistify/Rocket.Chat#353]
**Steps to reproduce**

 - set profile language to english (or any other than german)
 - write a german message
 - reply to the german message, the original message will be displayed in your profile language

![image](https://user-images.githubusercontent.com/11913979/41342966-b881da26-6efd-11e8-8069-04c798f26471.png)

**Comment by vickyokrm** [comment]
@ThomasRoehl am unable to reproduce the issue in dev environment. Can we try to look for another occurrence?
