### ISSUE TITLE
Re-activate / Re-implement delta sync

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#368]
### Description:
Currently we have deactivated the delta synch, because it is/was related to the "stuck channels". Since we were able to fix the problem in other ways, we can now reactivate and test the delta synch.

### Target:
By implementing this issue, channels that are out-of-sync should heal themselves as soon as the knowledge base is opened or a new message is written in a room.

**Comment by ThomasRoehl** [comment]
done
