### ISSUE TITLE
Shifting an email conversation to Assistify

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#399]
E-Mail is predominant and for new teams it is pretty tough to shift communication from email to Assistify. Hence we should offer a way to easily shift communication from mail to chat.

_First concept_

![email-to-chat](https://user-images.githubusercontent.com/3596824/42692213-2bc6d47c-86ab-11e8-959e-332473c575a4.jpg)

**Comment by jschirrmacher** [comment]
See #513 - maybe a duplicate?

**Comment by janrudolph** [comment]
**Job Story:**
_When a complex customer inquiry is sent to my personal email inbox, I want to discuss this issue immediately with my colleagues so that I can reply quickly with a high-quality response._ 

**Acceptance criteria**
- Users are able to forward an email to Assistify. 
- When forwarding users are able to specify: 
..- which members they would like to invite to the discussion. 
..- the parent channel of the disuccsion.
- The forwarded email will create a new channel / private group (tbd) in Assistify. 
- The members are invited automatically.
- The email text is displayed as first message in a channel. It is formatted as multi-line cite. 
- If the user invites people, who are not registered in Assistify, these people will get an invitation to join Assistify. A short notice in the newly created channel will inform the user that the system has invited these people. 
  

Possible solutions:
- Forward mail by simply send the mail to a specified email adress, e.g. `TO: assistify.mail.inbox@assistify.de`
- By adding email addresses in the CC-field of the mail, the specified people will be invited to the newly created channel `CC: max.muster@assistify.de; sarah.muller@assistify.de`.  
- Specifing the parent discussion could be implemented by adding a hashtag followed by the parent channel name to the subject field of the email, e.g. `#parent-channel-name`
- Alternative to using the TO, CC and subject fields: Create an MS Outlook plugin which enables users to select all properties in a form-based user interface.
- More inspiration: https://help.evernote.com/hc/de/articles/209005347-Speichern-von-E-Mails-in-Evernote

**Comment by ruKurz** [comment]
**Challenges**

- If the users do not use Assistify to lead the discussion, but remain in their usual email medium and do not remove the email address from TO, CC, a new discussion is created for each mail. To prevent this, there are several ways to handle only mails that meet certain conditions:
  - if the mail has been forwarded
  - if the TO/CC contains only the mailbox address
- Make sure that no discussion is being created in the following cases
  - Direct Reply messages, 
  - Mails that are simply written to the mailbox, 
  - Mail delivery news
  - Absence notifications (the mailbox is also used for notifications)
- It is technically hard to handle attachments (node lib, multipart mails, trigger upload, ...)
- formatting messages as multi-line cite

**Questions**

- Should it be possible to activate / deactivate this feature via configuration?
- Should a discussion be started for e-mails that are **forwarded** to the corresponding mailbox or for **every mail** that goes to the designated mailbox? (I assume that at least direct reply emails should not create a new discussion.)

**Comment by ruKurz** [comment]
Some information about the technical status for the implementation of the issue:

Essentially, that's two PRs to Rocket.Chat:
- https://github.com/RocketChat/Rocket.Chat/pull/14493 (already in Rocket.Chat)
- https://github.com/RocketChat/Rocket.Chat/pull/14697 (waiting for approval)

In addition, I had provided a PR, which was somewhat more extensive and shows how to implement further actions such as "Create a channel via Mail". This PR helps to find the right places in the code:
- https://github.com/RocketChat/Rocket.Chat/pull/14352 (closed, because not finished)

Otherwise I played around a bit on localhost. There I implemented the possibility to create a new room with a mail whose subject ends at room:<newRoomName>. The e-mail content will be used as the first message. The changes can be found on github in the branch direct-reply-by-subject:
- https://github.com/assistify/Rocket.Chat/tree/feature/direct-reply-by-subject

**Comment by janrudolph** [comment]
> **Challenges**
> 
> * If the users do not use Assistify to lead the discussion, but remain in their usual email medium and do not remove the email address from TO, CC, a new discussion is created for each mail. To prevent this, there are several ways to handle only mails that meet certain conditions:
>   
>   * if the mail has been forwarded
>   * if the TO/CC contains only the mailbox address
> * Make sure that no discussion is being created in the following cases
>   
>   * Direct Reply messages,
>   * Mails that are simply written to the mailbox,
>   * Mail delivery news
>   * Absence notifications (the mailbox is also used for notifications)
> * It is technically hard to handle attachments (node lib, multipart mails, trigger upload, ...)
> * formatting messages as multi-line cite
> 
> **Questions**
> 
> * Should it be possible to activate / deactivate this feature via configuration?
> * Should a discussion be started for e-mails that are **forwarded** to the corresponding mailbox or for **every mail** that goes to the designated mailbox? (I assume that at least direct reply emails should not create a new discussion.)

I added the major points to the acceptance criteria above.

**Comment by ThomasRoehl** [comment]
Since we don't want to modify RC code, they whole direct reply feature can not be used to implement this feature.

**Comment by janrudolph** [comment]
done by https://github.com/assistify/outlook-plugin
