### ISSUE TITLE
Implict chatpal search in all channels

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#403]
We realized that users do not use requests and topics. Instead they chat in long ongoing conversations. Due to that we cannot offer any value with our knowledge base since users simply do not have access to it. 

In order to deliver value with our knowledge base we have to activate it in any channel, like public and private groups, as well as, private chats. We should not store any conversation data, but display related content based on chatpal search. For instance, we could analyze the last 5 messages and search for the relevant keywords in chatpal. 

**Acceptance criteria:**
- Activate the knowledge base in all channels
- Provide just one common knowledge provider (chatpal) and team-specific knowledge providers (e.g. wikis)
- Analyze just the last X messages (e.g. five)

**Comment by ruKurz** [comment]
This feature will be implemented by introducing a Chatpal query provide for Smarti:

- https://github.com/redlink-gmbh/smarti/issues/274
- https://github.com/redlink-gmbh/smarti/issues/275
- https://github.com/redlink-gmbh/smarti/issues/276

**Comment by ThomasRoehl** [comment]
done
