### ISSUE TITLE
Sending reports 

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#404]
One of our value proposition is "saving time, search less". To show, that we delivered this value, we should send weekly/monthly/regular reports about the personal time savings to each user. Those reports could include:

- Number of users of you connected with
- Number of unwritten e-mails / Number of saved characters in comparison to mails
- Time saved because of searches in Assistify
- Total amount of time saved
....

We should add a like button as well in order to get some feedbacks on the report.

The most important point is that these reports have to be funny and ironic. Users should smile when they read the report.

**Comment by ThomasRoehl** [comment]
We can also give information about the most discussed topics with the associated channels, in order to guide people to make knowledge transfer in public channels instead of only writing direct messages
