### ISSUE TITLE
One-click login

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#406]
If users get an invitation to join Assistify, the initial login must be as simple as possible. 

Usually the invitation is sent by email.  By pressing the join link in the mail, the user should be logged in directly. The user should not click on any button like "click here for SSO login". In case the user cannot login by SSO, we should provide a similar experience.

**Comment by ruKurz** [comment]
I think that this is the case. But this requires
a) enabled auto register by identity service
b) valid SSO token within your browser's session

### Steps to proceed:
1. Open a browser
2. Login to some other SSO supported application (social intranet, enterprise search, ...)
3. Click a E-Mail link pointing to Assistify

**Comment by jschirrmacher** [comment]
I tried that with DB Systel Wiki and with DB Search but automatic login in Assitify doesn't work.
