### ISSUE TITLE
Set-Up wizard for users

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#407]
**Challange:**
For new users, especially for non-tech guys, it is pretty hard to start using Assistify. One reason might be, that users do not know the content and people who are involved in the team. 

**Possible Solution:**
Let us provide an set-up wizard for users at the first login. The purpose of the wizard is to list all channels and people a user might be interested in. By this, an user can chosse interesting content and the user will be subscribed to these channels/users automatically. The user gets therby a personalized version of Assistify when logging in the first time.

**Mockup:**
_in production ;-)_

**Comment by mrsimpson** [comment]
At the heart of this wizard, there is a way to manage subscriptions.
This could be very well integrated into the directory: Subscribed rooms could be listed there for un-subscription, similarly the listed channels and users could be used in order to subscribe to them.
