### ISSUE TITLE
Simplify Assistify Usage

### ISSUE THREAD

**Issue by ThomasRoehl** [assistify/Rocket.Chat#411]
For normal users remove all unnecessary icons:
- My Rooms
- All Rooms
- View Mode
- Sort
- New Channel
- Room Info
- Mentions
- Starred Messages
- Keyboard Shortcuts
- Pinned Messages
- Notification Preferences

Merge duplicated features to one:
- Member List
- Add User

Move all User configurable settings into the User Profile.

Remove Requests, Topics and make Knowledgebase available in normal rooms and direct chat.

Combine Search and Knowledgebase into one single feature.
Make Search more visible like the Knowledgebase in Requests.

Make markdown language icons more visible and add icons from the message options menu.
Remove message options menu.

This is related to https://github.com/assistify/Rocket.Chat/issues/403 and https://github.com/assistify/Rocket.Chat/issues/397

**Comment by jschirrmacher** [comment]
Request and topics are already removed now. Knowledgebase is available in all channels but not yet in direct chat.
