### ISSUE TITLE
Assistify-AI in all channels

### ISSUE THREAD

**Issue by mrsimpson** [assistify/Rocket.Chat#419]
# Motivation

Until now, we only activated the knowledge-base tab in requests and topics. Since this structuring conversations was not intensively used, many users of Assistify could not experience the added value of Smarti analyzing conversations.

With #418, requests and topics are not needed anymore in order to chat with people who know. Consequently, we need to find a way to provide value in ongoing discussions. The first-step AI-part for Smarti has been described in https://github.com/redlink-gmbh/smarti/issues/273

# Requirements

- [X] The Smarti-Widget shall be alive on a tab in all room types (except private rooms)
- [X] Smarti shall receive all messages in public channels (type `c`) in order to be able to create a team's body of knowledge
- [X] Consequently, the AI component has to be able to react on a room type being changed: The information of a room being either publically readable or whether it should not be returned from the knowledge base has to be respectable when returning results.
- [X] Theremost not be any dependency towards requests and topic room types, events or properties anymore

**Comment by mrsimpson** [comment]
Remark: For the restriction of results from Smarti to public channels (or precisely readable information to the one asking), there are actually multiple possibilities:

- Propagate only public channels, delete private groups in Smarti. Challenge: What happens if Smarti is unavailable at the time of room type change?
- Validate the authorization to view the result of a non-public channel when returning the results. Challenge: This would have to be done on the server side, since client side filtering is insecure.
- Adapt Smarti to filter the results at the Smarti side. Challenge: Small change to Smarti on all stacks (Web-API down to the collection schema in Solr)

**Comment by ruKurz** [comment]
This should be resolved by releasing `less-is-more`
