### ISSUE TITLE
Copy expertise from external system on API-based creation

### ISSUE THREAD

**Issue by mrsimpson** [assistify/Rocket.Chat#42]
If a help request has been created by the [API](https://github.com/mrsimpson/Rocket.Chat/blob/master/packages/assistify-help-request/server/api.js#L116), the consumer of the API has some mechanism to select users which shall be joined  to the room as experts.
If the context passed via the API includes an expertise, 

* ...this expertise be dynamically created in RC if it didn't exist.
* ...adjusted to the set of users provided via the API-call.

**Comment by janrudolph** [comment]
might be obsolete if we accomplish https://github.com/assistify/Rocket.Chat/issues/337
