### ISSUE TITLE
Can't set a profile picture

### ISSUE THREAD

**Issue by jschirrmacher** [assistify/Rocket.Chat#435]
### Description:

I upload a profile picture and after saving, it is shown in my profile as expected. But after closing the profile, it is not shown in the chat. When I click on the profile again, the picture is gone.

I tried this with an URL as well, but the effect is the same. I also tried with both, the web client and the app, and still the same result.

There are no messages in the Web console, not even a network access when saving the changes in the profile.

### Client Information:

* Operating System: OSX 10.13.6
* Browser: Chrome 68.0.3440.106
* Rocket Chat App Version: 2.12.2

### Steps to Reproduce:

1. Upload a profile picture
2. Save
3. Close profile

### Expected behavior:

The profile picture is used in the chat.

### Actual behavior:

It isn't. When opening the profile again, the picture is gone.

### Relevant logs:
There is nothing logged in the web console, not even a network access when saving the changes in the profile.

**Comment by jschirrmacher** [comment]
I cannot reproduce this behaviour in the most current version.

**Comment by jschirrmacher** [comment]
I can reproduce the problem in the most current Team Chat, and so did @ruKurz. Seems like it has something to do with this special installation.

**Comment by ruKurz** [comment]
This might be related to #475

**Comment by ruKurz** [comment]
@jschirrmacher How did you test this issue? Please try via a plain internet connection using chrome.

**Comment by ruKurz** [comment]
There occurs an error on the server side while saving the profile:
```
[34mI20180912-14:10:12.858(0) Error while handling the setting of the avatar from a url (https://cloud.netlifyusercontent.com/assets/344dbf88-fdf9-42bb-adb4-46f01eedd629/242ce817-97a3-48fe-9acd-b1bf97930b01/09-posterization-opt.jpg) for ThomasR: { Error: getaddrinfo ENOTFOUND cloud.netlifyusercontent.com cloud.netlifyusercontent.com:443     at errnoException (dns.js:50:10)     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)    code: 'ENOTFOUND',   errno: 'ENOTFOUND',   syscall: 'getaddrinfo',   hostname: 'cloud.netlifyusercontent.com',   host: 'cloud.netlifyusercontent.com',   port: 443 } 
```

**Comment by jschirrmacher** [comment]
I can reproduce this with plain internet connection using chrome. Picture upload works now, but not using an URL.

After inserting the URL and pressing the link button the picture is shown at first. Even when I click on save, the picture is still visible. But if I change to another page and then go back to the profile, the picture is gone.

There are no errors in the browser console but in the server log. The problem seems to be related to our local environment which cannot access external URLs:
```Error while handling the setting of the avatar from a url (https://avatars3.githubusercontent.com/u/2821879?v=4) for joachim: { Error: getaddrinfo ENOTFOUND avatars3.githubusercontent.com avatars3.githubusercontent.com:443     at errnoException (dns.js:50:10)     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)    code: 'ENOTFOUND',   errno: 'ENOTFOUND',   syscall: 'getaddrinfo',   hostname: 'avatars3.githubusercontent.com',   host: 'avatars3.githubusercontent.com',   port: 443 } ```

**Comment by jschirrmacher** [comment]
It even does not work with URLs on the (internal) server with the same Rocket.Chat installation. (I upload a photo (which works) and then use the URL which is used in the chat.
