### ISSUE TITLE
Allow to select private channels as parent when creating a new thread

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#437]
### Auto invite

One of the main benefits of threads is, that the users/groups are invited dynamically to a specific discussion / sub conversation regarding a specific topic. A user who needs help or wants to discuss a certain topic does not need to create a new channel and then invite all the relevant participants separately. Instead he is enabled to auto-invite potential members of an existing group/room. 

### Start requests

Especially private rooms/groups represent a collection of persons that are working on a specific topic. If somebody from "outside" wants to ask this group of specialist is not able to contact the whole group without getting a member of the private group itself. If it would be possible to start a thread based on the members of a private group would result in two main advantages:

1. Sub conversations of a private group can be started easily (without re-selecting the members)
2. External people are able to start a request to any private group without becoming a member of the group itself

### Actual behavior

Currently new threads can only be created for public groups.

### expected behavior

New threads can be created by selecting a private group.

<img width="899" alt="bildschirmfoto 2018-09-04 um 11 29 06" src="https://user-images.githubusercontent.com/2821879/45022972-cb938c80-b035-11e8-905a-df406de1dffa.png">

**Comment by jschirrmacher** [comment]
When I create a new thread, I can select only public channels as the parent.

Instead, also private channels which the current user has access to should be proposed.
<img width="899" alt="bildschirmfoto 2018-09-04 um 11 29 06" src="https://user-images.githubusercontent.com/2821879/45022972-cb938c80-b035-11e8-905a-df406de1dffa.png">

**Comment by vickyokrm** [comment]
@ruKurz This feature is already part of the `less-is-more`. If the user has a Permission `view-other-user-channels` then the private rooms will be listed for parent channel selection.

**Comment by janrudolph** [comment]
obsolete with RC 1.0.0
