### ISSUE TITLE
Add support to format the message when creating a new thread via the dialog

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#438]
In many cases a thread starts with some input information e.g. an image, a code snippet, a cite, ... Therefore the input field for entering the initial message of a new thread in the create dialog should support more advanced text formatting options.

### Actual behavior

Currently the "create new thread dialog" provides a simple `textarea` to enter the first message.
<img width="684" alt="bildschirmfoto 2018-09-04 um 11 32 10" src="https://user-images.githubusercontent.com/2821879/45023182-42308a00-b036-11e8-9c5b-ed15432850c5.png">

### Expected behavior

The "create new thread dialog" provides more advanced text formatting features to enter the first message. 

### Possible solution

Maybe it is possible to make reuse of the regular chat message input field, including all the options:
- Upload an image
- Selecting emojis
- Formatting options for code, bold, cite, ...

**Comment by jschirrmacher** [comment]
The input field when creating a new thread is a simple <textarea> without any formatting functionality. There should be the same formatting functionality as in the regular input field.

<img width="684" alt="bildschirmfoto 2018-09-04 um 11 32 10" src="https://user-images.githubusercontent.com/2821879/45023182-42308a00-b036-11e8-9c5b-ed15432850c5.png">
