### ISSUE TITLE
The link to select a parent for a new thread should be more prominent

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#439]
Currently, the text is light grey on white background. The link itself is a little darker, but still very likely to be overseen by the user.

<img width="644" alt="bildschirmfoto 2018-09-04 um 11 34 00" src="https://user-images.githubusercontent.com/2821879/45023386-a5222100-b036-11e8-92fd-8e518815be2e.png">

I recommend to remove the link and use the selection box in the first place.

**Comment by jschirrmacher** [comment]
Currently, the text is light grey on white background. The link itself is a little darker, but still very likely to be overseen by the user.

<img width="644" alt="bildschirmfoto 2018-09-04 um 11 34 00" src="https://user-images.githubusercontent.com/2821879/45023386-a5222100-b036-11e8-92fd-8e518815be2e.png">

I recommend to remove the link and use the selection box in the first place.
