### ISSUE TITLE
Remove black bars beneath "new request dialog"

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#44]
UI Improvement
Please remove the black bars beneath the "new request dialog" (see screenshot).
![28323837-2f97c526-6bda-11e7-86f3-4e611c834e1f](https://user-images.githubusercontent.com/853776/30809980-d4cd7310-a203-11e7-9529-3f42768a0587.png)

**Comment by mrsimpson** [comment]
Obsolete with new UI
