### ISSUE TITLE
announcements should strip the code formatting (at top of a channel and in the channel info)

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#440]
Formatting is great, but it should at least handle it correctly, if, for example, someone uses pre-formatted multi-line code like in the current screenshot:

<img width="983" alt="bildschirmfoto 2018-09-04 um 11 44 47" src="https://user-images.githubusercontent.com/2821879/45023959-1a422600-b038-11e8-855c-9de3e40553ab.png">

If this is not so easy, it would be an improvement if code formatting would be stripped when using the text for the new thread as the global announcement. When editing the thread information, multi-line text is prevented, so there doesn't need to be changed anything.

**Comment by jschirrmacher** [comment]
Formatting is great, but it should at least handle it correctly, if, for example, someone uses pre-formatted multi-line code like in the current screenshot:

<img width="983" alt="bildschirmfoto 2018-09-04 um 11 44 47" src="https://user-images.githubusercontent.com/2821879/45023959-1a422600-b038-11e8-855c-9de3e40553ab.png">
