### ISSUE TITLE
Improve links/info when deleting a thread or when a user is not permitted to access the thread

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#442]
If a thread is deleted, the link remains in the parent channel (it is not clickable, but exists). Also, the parent channel reader receives no information that the thread has been removed. Optimally, at the point where the thread was branched off, an info is displayed that the sub conversation no longer exists.

- If the user does not have sufficient permissions, the "Ask to join" feature will help along.
- If the channel does not exists (e.g. deleted) the user should get an information within the parent channel

**Comment by jschirrmacher** [comment]
At least, as long as the link to the thread in the parent channel doesn't to anything, I regard this issue as a bug.
