### ISSUE TITLE
create thread dialog: Show channel display name instead technical name

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#446]
### Description:

When selecting a channel for a thread within the create channel dialog Currently the technical name of a channel is displayed. Instead the display name should be used.

### Steps to Reproduce:

1. Create a new thread via the dialog
2. Click on "select the parent channel"
3. Start typing a channel name
4. Compare the input suggest options (technical names) with the display names

### Expected behavior:

The display name is being used.

### Actual behavior:

The technical name is being used.

<img width="1226" alt="_ __assistify_team_chat" src="https://user-images.githubusercontent.com/853776/45023034-eb2ab500-b035-11e8-9fe5-53be9c9cc398.png">

**Comment by vickyokrm** [comment]
@ruKurz Display names can be non-unique and ´General´ channel do not have display name property. Therefore, I would like to keep the autocomplete to suggest the technical name which can remain unique.
