### ISSUE TITLE
Update topic in rooms does not affect children or smarti

### ISSUE THREAD

**Issue by ThomasRoehl** [assistify/Rocket.Chat#447]
What should happen if someone changes the title/label of the parent room? Do all children become updated? The label of the topic filter does not reflect changes to the title or topic of the parent channel. Fixing this issue needs a synchronization between RC and Smarti if any meta data of a channel is being edited.

**Comment by ruKurz** [comment]
If the links between parent and child are kept intact (based on room ids), the main goal is achieved. 
From the user perspective, displaying out dated labels is always misleading. Therefore, this issue is  an valid improvement.

**Comment by ruKurz** [comment]
TODO: Disambiguate between topic and room channel. And create different Issues: One focusing on the Smarti Filter and one that discusses the links between the parent and child channel.
