### ISSUE TITLE
Open Smarti Widget in threads by default

### ISSUE THREAD

**Issue by ThomasRoehl** [assistify/Rocket.Chat#448]
Should the knowledge base pop up if someone enters a new thread (requires the new thread PR before)?

**Comment by mrsimpson** [comment]
Threads are not special compared to normal rooms: As soon as Smarti can make some sense of it, it should open the tab. No special behavior is necessary in my opinion

**Comment by ruKurz** [comment]
We decided to not open the knowledge base now.
