### ISSUE TITLE
Default topic for new channels

### ISSUE THREAD

**Issue by ThomasRoehl** [assistify/Rocket.Chat#450]
In a regular channel (private/public) there will be no suggestions as long as you deactivate the Smarti topic filter. This problem can be solved by setting the topic to the name of the channel by default. Then all messages from threads (children) will be suggested in the channel (parent).

@mrsimpson Do you have any ideas how to extend RocketChat.createRoom() in order to set a topic by default without changing the RC core?

**Comment by mrsimpson** [comment]
I don’t think that setting a default topic in the chat is the proper solution, but only a workaround. I’d rather say that the widget should set the current room name as optional filter if no topic is given and deactivate it be default

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ruKurz** [comment]
This is a Smarti related issue. The default filter:
https://github.com/redlink-gmbh/smarti/issues/280
