### ISSUE TITLE
Magnifying glass in left column

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#456]
Will we ship the magnifying glass in the left column? So far, we removed it?

![lupe](https://user-images.githubusercontent.com/3596824/45031586-854b2700-b04f-11e8-8932-01d6b8f6a6b1.PNG)

**Comment by ruKurz** [comment]
We decided to re-use the inbox symbol as long there is no change from the feature perspective.

**Comment by ruKurz** [comment]
is already pushed to `develop`
