### ISSUE TITLE
Positioning of create new thread button

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#458]
![ungelesen](https://user-images.githubusercontent.com/3596824/45031636-b0357b00-b04f-11e8-87e6-12ca505415f5.png)

I do not like the positioning of the button when an user has some favourites or if there are unread messages. The button looks incorrectly positioned. Placing the button right beneath the top left icons would look cleaner.

**Comment by ruKurz** [comment]
This has been pushed to `develop`
