### ISSUE TITLE
Rename label for "bulk-register-users"

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#46]
Rocket.Chat Version: 0.58.1

Permission `bulk-create-c` and `bulk-register-users` have the same label `Bulk create channels`. 

**Please verify with current Rocket.Chat version.**

**Comment by mrsimpson** [comment]
Fixed some time ago with the new translations
<img width="239" alt="bulk" src="https://user-images.githubusercontent.com/17176678/31511138-1018bfb6-af87-11e7-9034-9c384eba00d6.png">
