### ISSUE TITLE
Merge threads with regular channels in the channel list

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#460]
I would prefer merging the threads with all other channels in the channel list. In the end, threads are public or private channels. We do not need a special category for them in the left channel list. Having a dedicated section for threads adds complexity and does not add extra value. 

We should at least allow users to merge the threads with the other channels by making use of the sidebar feature "group by type".

**Comment by ruKurz** [comment]
@mrsimpson fixed this issue: If you now select group by type the threads have their own section in the left-hand panel. The button for create a new thread is always on top now.
