### ISSUE TITLE
[Proxy] Implement password policy (configuration)

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#47]
The password must be chosen in such a way that it is difficult to guess and easy to remember. Passwords such as names, license plates, birth dates, words from dictionaries and other trivial passwords ("BBBBBB","123456", etc.) are not allowed.

The password must be at least eight characters long, if technically possible, and

at least one special character (a character containing
is neither a letter nor a number, for example
- !"§$%&/ (){}[]?.,: -_#+*<>),
- contain at least one digit (0-9), and
- contain at least one capital letter and

**Comment by ruKurz** [comment]
A password history prevents at least the re-use of the last 5 passwords in case of password changes and forces a change of at least 5 characters compared to the last one.

**Comment by janrudolph** [comment]
see https://github.com/RocketChat/Rocket.Chat/pull/9857

**Comment by mrsimpson** [comment]
Cheery-pick https://github.com/RocketChat/Rocket.Chat/pull/9857
