### ISSUE TITLE
User role labels are not correct

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#476]
![admin-user-role-names](https://user-images.githubusercontent.com/3596824/45287599-f2940780-b4e8-11e8-8e34-c863d087cbb4.PNG)

The label looks like a technical description. We should change this to a user-friendly description.

**Comment by ruKurz** [comment]
<img width="585" alt="bildschirmfoto 2018-09-10 um 14 26 05" src="https://user-images.githubusercontent.com/853776/45297393-84117280-b505-11e8-8af5-507c24def329.png">

This is a configuration. We must make sure. Those configs are correct in production.

**Comment by ruKurz** [comment]
@janrudolph could you please check that this configuration is set correctly within the scripts?
