### ISSUE TITLE
misplaced `leave` button in the room info tab

### ISSUE THREAD

**Issue by ThomasRoehl** [assistify/Rocket.Chat#479]
Wrong element placement and missing translation
![image](https://user-images.githubusercontent.com/11913979/45289431-6a643100-b4ed-11e8-873e-91d9bf909b13.png)

**Comment by ruKurz** [comment]
Created a separated issue for the Admin UI corrections:
https://github.com/assistify/Rocket.Chat/issues/490

**Comment by ruKurz** [comment]
Is this a Rocket.Chat core issue? Or is this some side effect by changing styles for the Smarti Widget? I think we did not change anything in the room info dialog.

**Comment by ThomasRoehl** [comment]
When you move the leave-button down it fits nicely also in german language
![image](https://user-images.githubusercontent.com/11913979/45358690-84c00c80-b5ca-11e8-8229-77c8268e3cf8.png)

**Comment by ruKurz** [comment]
tested successfully on `develop` (team chat).
