### ISSUE TITLE
Desktop notifications are not shown every time.

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#48]
_From @ruKurz on September 25, 2017 13:41_

Reported by HMP
ANALYSE: Notification Pop-Up erscheint nicht immer, analysieren

https://github.com/mrsimpson/Rocket.Chat/issues/94

_Copied from original issue: assistify/assistify.github.io#2_

**Comment by ruKurz** [comment]
We should talk to our customer and ask if this issue still persists. If not, we can close this issue.

**Comment by janrudolph** [comment]
@ruKurz Can we close this issue?
