### ISSUE TITLE
OTR key icon is mssing

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#481]
Before:

![rocket_chat](https://user-images.githubusercontent.com/3596824/45290289-88cb2c00-b4ef-11e8-8db2-c8b8bd20949b.png)

Now, the green key icon is not displayed anymore.

**Comment by ruKurz** [comment]
I removed the milestone, since this is not related with the `less-is-more` release. Moreover this seems to be a Rocket.Chat core issue.
