### ISSUE TITLE
[BUG] Threading: after deleting the thread, the message in the parent channel doesn't get deleted

### ISSUE THREAD

**Issue by ThomasRoehl** [assistify/Rocket.Chat#483]
When creating a thread from a message or via the 'start thread' button a bot message is sent in the parent channel.
This message persists even when the thread is deleted and the room link doesn't work anymore (nothing happens on click)

**Comment by ruKurz** [comment]
duplicates: https://github.com/assistify/Rocket.Chat/issues/442
