### ISSUE TITLE
"Agent_typing_alias" is not used anymore

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#484]
We missed merging https://github.com/assistify/Rocket.Chat/pull/374. We introduced a new feature which enables admins to set a "Agent_typing_alias" globally. 

It seems to be not critical right now since we now use RocketChat 0.68 which allows using real names for live chat agents (https://github.com/RocketChat/Rocket.Chat/pull/11164).

**Comment by ruKurz** [comment]
I would suggest to remove the milestone or to change it to `less-is-more-rework`.
@janrudolph do you think we need to tackle this issue in the course of the upcoming release?

**Comment by ruKurz** [comment]
this feature is obsolete
