### ISSUE TITLE
[Config] Use subtle color for "choosing parent channel"

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#485]
![rocket_chat](https://user-images.githubusercontent.com/3596824/45299201-19fbcc00-b50b-11e8-952f-19f20903cb9e.png)

**Comment by ruKurz** [comment]
This is related to:
https://github.com/assistify/Rocket.Chat/issues/439
We will focus this after the upcoming release, therefore I changed the milestone to `less-is-more-rework`
