### ISSUE TITLE
User is only redirected via the message link when already member of the target room

### ISSUE THREAD

**Issue by ThomasRoehl** [assistify/Rocket.Chat#489]
The Link in the system message to go to the parent or the thread is only working for users which are member of the target room. Otherwise nothing is happening (no error message or any hint)

**Comment by ruKurz** [comment]
This should be fine for private rooms, but if you're creating a thread as child of an public channel, the link should work even one is not a member of the parent room.

**Comment by ruKurz** [comment]
tested successfully on develop (team chat).
