### ISSUE TITLE
Messages in threads on private channels are not visible for all users in the thread

### ISSUE THREAD

**Issue by jschirrmacher** [assistify/Rocket.Chat#504]
### Steps to reproduce:

1. I create a private channel 'js-test' and create a direct link to create a thread in this channel (as used by BusinessHub team)
2. Another user uses this link to create a thread - which works, he is member of this channel then.
3. He types some messages in this channel and sees this messages, I see them as well.
4. I answer back and see my messages too, but he doesn't see them.

### Expected behavior:

The other user should see my messages too.

### Actual behavior:

The other user sees only his own messages.

### My screen
<img width="1101" alt="bildschirmfoto 2018-09-12 um 17 50 14" src="https://user-images.githubusercontent.com/2821879/45471336-15186180-b731-11e8-9057-ad3479ef8458.png">

### Screen of other user at the same time
<img width="1623" alt="screen shot 2018-09-12 at 17 49 40" src="https://user-images.githubusercontent.com/2821879/45471331-121d7100-b731-11e8-9da9-fd738a83eab3.png">

**Comment by Morl99** [comment]
As just noted in your team channel, this is a high priority issue for us, as we need this feature to work as a replacement for the now missing requests.

**Comment by jschirrmacher** [comment]
Might be solved with #443

**Comment by ThomasRoehl** [comment]
A workaround is to refresh the page.

**Comment by jschirrmacher** [comment]
Confirmed that the problem is solved with #443
