### ISSUE TITLE
Message input field does not expand, when a suggestion has been selected

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#51]
Issue
When you select information from the Knowledge Base, it is pasted in the text field. However, the size of the text field does not automatically adjust to the size of the text that is pasted from the Knowledge Base. The size gets adjusted when you click in the text field and navigate in it.

Solution
Adjust the size of the text field after selecting information from the Knowledge Base so that the whole text is visible in the text field.

Replaces: https://github.com/mrsimpson/Rocket.Chat/issues/74

**Comment by ruKurz** [comment]
@janrudolph this is not a duplication.
#63 says that the knowledge base tab bar does not appear wehen selecting a reuqest
#74 says that the message field is not expanding, when a suggestion has been selected from the knowledge base.

I think this issue could have been solved by #62, since the expansion of the message box is most probably triggered by the same event as the send icon is being triggered.

So we should test, if this issue still persists.

**Comment by janrudolph** [comment]
@vickyokrm Is this issue solved?

**Comment by vickyokrm** [comment]
@janrudolph It is resolved and PR was raised to merge quite sometime back.

**Comment by vickyokrm** [comment]
Tested again in our team chat version, this issue was resolved with the message box auto grow as expected when a conversion was copied
