### ISSUE TITLE
News Bot

### ISSUE THREAD

**Issue by ThomasRoehl** [assistify/Rocket.Chat#511]
Mögliche Anwendungsfälle:

- Polizei / Erziehungsbot: Ein Bot weist auf Features hin, die das Arbeiten im Team verbessern, bspw. nutze Threads, pin doch mal eine Nachricht, ...
- Smarti Bot: Ein Bot pusht aktiv Informationen zu Usern, bspw. auf Basis der Chatpal Suche. Dies kann direkt im Moment des Chats oder später folgen, nach dem Motto "das könnte dich auch interessieren"

Wir sollten uns für beide Bots Anwendungsfälle überlegen, die interessant sind für Nutzer. Zudem ist es notwendig für jeden Fall eine Möglichkeit zum (manuellen) Testen zu entwickeln. Die Tests müssen mit wenig Aufwand durchführbar sein.

**Comment by janrudolph** [comment]
Maybe related to https://github.com/assistify/Rocket.Chat/issues/91
