### ISSUE TITLE
We need a Way to close a thread

### ISSUE THREAD

**Issue by ThomasRoehl** [assistify/Rocket.Chat#518]
There is currently no way to close a thread as a normal user.
Only admins can delete or archive the room.

Suggestion:
![2018-09-18 11 06 02](https://user-images.githubusercontent.com/11913979/45677012-72e2ea00-bb33-11e8-9b62-48f163bcd55c.gif)

**Comment by mrsimpson** [comment]
Now that threads are merged into the next version of RC, I created a core issue for it: RocketChat#13664
