### ISSUE TITLE
Smarti Widget is not displayed, if a user reloads, reopens or enters a help request

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#52]
Issue Statement:
It is expected to show the historic conversation window expanded as default for the chat user.

**Comment by ruKurz** [comment]
@vickyokrm This should be default on browser, but not on mobile.
Can you confirm that this issue persists?

**Comment by ruKurz** [comment]
Replaces: https://github.com/mrsimpson/Rocket.Chat/issues/63

**Comment by vickyokrm** [comment]
This issues is fixed. Tested again in the team chat version,  as i could see the smarti widget displayed default on the browser(chrome and IE) but not on the mobile device.

**Comment by vickyokrm** [comment]
(referring to the previous comment) Therefore, closing the issue.
