### ISSUE TITLE
[Proxy] Custom room types (Rocket.Chat#8246)

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#55]
https://github.com/RocketChat/Rocket.Chat/issues/8246

**Comment by cyclops24** [comment]
@ruKurz what is this feature state?
I saw below image in #75 and I reeeeeeeeeeealy love this idea:
![8](https://user-images.githubusercontent.com/17176678/31254127-ac5a24ba-aa27-11e7-863a-3aac6dc67da8.png)

**Comment by ruKurz** [comment]
According to the linked Issue https://github.com/RocketChat/Rocket.Chat/issues/8246
there is an open PR: https://github.com/RocketChat/Rocket.Chat/pull/8274, that is already approved, but not merges yet. Looks good that this feature will be part of the RC core, soon.

@mrsimpson and the colleagues from Rocket.Chat are working on it.

**Comment by mrsimpson** [comment]
@cyclops24 Thx! Feedback appreciated - even if it's not only applause ;)
What do you like about the idea? I created a group on open.rocket.chat in order to continue this discussion

**Comment by cyclops24** [comment]
Hi,
Guys what is the **custom room type** feature state?

**/CC:** @mrsimpson, @ruKurz

**Comment by graywolf336** [comment]
It's been merged: https://github.com/RocketChat/Rocket.Chat/pull/9009

**Comment by cyclops24** [comment]
Thanks @graywolf336 It's on API level or UI also merged?

**Comment by janrudolph** [comment]
closed (see RocketChat#8246)
