### ISSUE TITLE
Electron App: Strange text conversion when using inline-code and hyphens

### ISSUE THREAD

**Issue by jschirrmacher** [assistify/Rocket.Chat#574]
### Description:

When sending single quotes in combination with hyphens, the text is converted to a strange string surrounded by '=!='. This doesn't happen with triple-quotes (multi-line).

### Steps to reproduce:

In a private channel (might happen in public ones as well, but I didn't check) type `\`text-text\`` and send the message.

### Expected behavior:

The text should be shown.

### Actual behavior:

A obviously random string is printed, and the content changes every time the page is reloaded.
<img width="360" alt="bildschirmfoto 2019-02-15 um 11 34 49" src="https://user-images.githubusercontent.com/2821879/52851211-ccb50380-3115-11e9-9833-cea0726ff047.png">

### Server Setup Information:

- Version of Rocket.Chat Server: 0.71.1
- Operating System: Linux
- Deployment Method: docker
- Number of Running Instances: 3
- DB Replicaset Oplog: 
- NodeJS Version: v8.9.4
- MongoDB Version: 

![clipboard - 15 februar 2019 11-24](https://user-images.githubusercontent.com/2821879/52851301-0a199100-3116-11e9-94be-fba68c056ea3.png)

**Comment by mrsimpson** [comment]
This is not an issue of an app, but of highlighting in a Markdown rendered message.
However, it only occurs if *Marked* ist configured as parser.
