### ISSUE TITLE
Mit bestimmte Sortierung Einstellungen werden Questions nicht angezeigt

### ISSUE THREAD

**Issue by DmytroPuzhay** [assistify/Rocket.Chat#582]
Ich habe folgende Sort Einstellungen in Assistify:
- Activity
- Group favorites
- Unread on top

Damit werden Questions links (wo Conversations usw angezeigt werden) gar nicht angezeigt, zb https://vendo.assistify.noncd.db.de/channel/rl-support-29 ich gestartet habe sehe ich dort nicht.

Als Workaround kann man kurz in Sort "Group by Type" einschalten, dann werden die Question unter "Questions" angezeit, soll aber natürlich auch ohne "Group by Type" angezeigt werden.
mal über das Sortier-Icon (über der Kanalliste zu finden) die Option "Gruppieren nach Typ" ein.

**Comment by jschirrmacher** [comment]
I can reproduce this behaviour. We will investigate further and plan a fix for that.

**Comment by ruKurz** [comment]
The concept of questions has been turned into "discussions" and "threads". Thereby a new sorting menu has been released:

![_5  Serviceeinheit Enterprise Cloud by Assistify](https://user-images.githubusercontent.com/853776/70433533-4b52a700-1a82-11ea-9f6b-84e6d5e00f6d.png)

Please re-validate if this is still an issue.
