### ISSUE TITLE
Es soll eine Möglichkeit geben in Channel alle Questions anzuzeigen

### ISSUE THREAD

**Issue by DmytroPuzhay** [assistify/Rocket.Chat#583]
In Prinzip wie in Summary geschrieben - das wäre ein Feature Request, ohne diese Möglichkeit ist es schwierig ein Überblick von Quesions in einem Channel zu bekommen.

**Comment by jschirrmacher** [comment]
Thank you for your request. We will take this into account when planning the next features.

**Comment by mrsimpson** [comment]
see a00e8266153f609968e00e023a9e468a4107ca1c
This could be cherry-picked and added to a PR for Rocket.Chat

**Comment by ruKurz** [comment]
This feature should be working right now. Since we've updated to RC1 long time ago.
