### ISSUE TITLE
[Feature Request] Display URLs as Links in Room Topics / Announcement

### ISSUE THREAD

**Issue by JanMosigItemis** [assistify/Rocket.Chat#591]
Hi there,

I'd like to have the UI rendering URLs in the topic and announcement section of a room as clickable links. This helps us to keep important stuff not only visible but also easily accessible to everyone in the room. Currently links must be manually copied and pasted (selecting the URL + right click might be enough in some browsers) which is inconvenient and might also reduce accessibility for people with disabilities.

**Comment by janrudolph** [comment]
@JanMosigItemis Thanks for your request! 

You can already use Markdown to generate clickable links. Please find Markdowns examples here: https://www.markdownguide.org/basic-syntax/#links

**Comment by JanMosigItemis** [comment]
Ah, didn't know that. Will try. 👍

**Comment by JanMosigItemis** [comment]
Ok, I tried it out and it really does work. So from my point of view, this is sufficient. Issue could be closed.

One minor thing: When klicking on markdown links in the channel's notification area ("Ankündigungen"), the link is opened, but so is also a pop up window displaying the markdown:

![image](https://user-images.githubusercontent.com/16935994/55723394-43c99280-5a09-11e9-89a8-f202d629c350.png)
