### ISSUE TITLE
Role-based requests

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#61]
Currently users are able to create requests for all available topics. However, this is not favorable in every situation. Imagine a team connects with external partners. The external partners should not be able to create requests for every topic. There might just be some topics which are relevant for the external partners. 

Preventing access to every topic helps to solve issue https://github.com/redlink-gmbh/smarti/issues/21 . We could focus on filters there. 

_Moved from_ https://github.com/mrsimpson/Rocket.Chat/issues/91

**Comment by janrudolph** [comment]
If we get rid of the topics and just enable creating requests out of regular channels, we do not need this story anymore. If we keep the topics, we should think about this story.

**Comment by jschirrmacher** [comment]
We don't have topics any more, so we could just close this issue, right?
