### ISSUE TITLE
Some notifications preferences don't work

### ISSUE THREAD

**Issue by DmytroPuzhay** [assistify/Rocket.Chat#613]
Following channel notifications preferences don't work as their description suggests:
1) Mute @all and @here mentions
2) Hide counter (Do not display any counter of this channel)

When turned on they don't have any effect - "@all/@here" still will highlight the channel and move it on top and "counter" still will be displayed.

**Comment by jschirrmacher** [comment]
I can reproduce this and created an issue in the underlying Rocket.Chat application:
https://github.com/RocketChat/Rocket.Chat/issues/14792
