### ISSUE TITLE
Images are not displayed after first click

### ISSUE THREAD

**Issue by DmytroPuzhay** [assistify/Rocket.Chat#636]
One click on the blue arrow near inserted image does not open it, second click is required.

**Comment by DmytroPuzhay** [comment]
Ping?

**Comment by jschirrmacher** [comment]
I cannot reproduce this problem. Does it still exist?
Please write in #Assistify channel of your chat if so, so that I can check in your actual installation.

**Comment by DmytroPuzhay** [comment]
The Problem is still reproducible, my #Assistify would be https://vendo.assistify.noncd.db.de/channel/assistify but I don't see you in members.

P.S. I use web client.

**Comment by ruKurz** [comment]
I can't reproduce this behavior. Clicking an image directly displays the picture (using chrome on MacOS). Can you please add "steps to reproduce"?

**Comment by ruKurz** [comment]
I removed the pictures from the initial description because those showed personal data.
