### ISSUE TITLE
Copy message from context menu not working correctly

### ISSUE THREAD

**Issue by DmytroPuzhay** [assistify/Rocket.Chat#644]
### Description:

"Copy" copies only comment text, but not the author/time. Related to https://github.com/assistify/Rocket.Chat/issues/616

### Steps to reproduce:

1. click ... near any comment
2. Copy
3. Paste

### Expected behavior:

Comment author/time + content is pasted

### Actual behavior:

Only comment content is pasted

**Comment by jschirrmacher** [comment]
Isn't that what the `Quote` command - or, if you want to 'copy' to another channel, the `Get Link` command - does? Or does at least help these commands do, what you want to do?

**Comment by DmytroPuzhay** [comment]
"Quote" just gives you a possibility to answer on the top level and not in a thread.

"Get link" copies the link to a comment as I understand, but sometimes I don't want to provide a link, eg when the comment was sent directly of in a private channel.

**Comment by jschirrmacher** [comment]
If you want to start a thread, then simply `Reply in Thread`.

So, actually, you need the change to copy a private message (which you can't link to), content together with its metadata to paste both in another channel.

**Comment by DmytroPuzhay** [comment]
I don't, I was just commenting on your **Quote** suggestion :)

Yes, that would be the most frequent case, but sometimes I also want to forward a single comment or some parts of discussion without forcing my companion to navigate/read everything else there.

I think that **Copy** actually used to work like that, but it got change ~1-2 Month ago.

**Comment by ruKurz** [comment]
This is a feature request with a low impact. Currently we'll not working on this actively.
