### ISSUE TITLE
The Assistify logo is not displayed in the below navigation bar

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#663]
The Assistify logo is not displayed below the conversations on the lower left. There should be the white Assistify logo again.

Version: `2.3.2-0.9.14`

<img width="555" alt="Bildschirmfoto_2020-02-11_um_16_07_36" src="https://user-images.githubusercontent.com/853776/74248981-c0439680-4ce8-11ea-8268-4cf8d87722c0.png">

**Comment by mrsimpson** [comment]
This is not a bug in code, but in our configuration.
<img width="611" alt="Bildschirmfoto 2020-02-11 um 19 35 10" src="https://user-images.githubusercontent.com/17176678/74267153-d449c100-4d05-11ea-87f4-f31a76072ae4.png">
