### ISSUE TITLE
[proxy] Potential threat - Unregistered LiveChat widget user is able to have a look in the backend #7725

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#67]
https://github.com/RocketChat/Rocket.Chat/issues/7725

**Comment by mrsimpson** [comment]
for discussions about solutions, please see https://github.com/RocketChat/Rocket.Chat/issues/7725#issuecomment-336213878 and following

**Comment by janrudolph** [comment]
Done with 0.61
