### ISSUE TITLE
[Proxy] Rocket.Chat Apps

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#72]
Proxy for https://github.com/RocketChat/Rocket.Chat/issues/6890

**Comment by janrudolph** [comment]
duplicate to https://github.com/assistify/Rocket.Chat/issues/57

**Comment by ruKurz** [comment]
@janrudolph I thought it would be a good idea to add the original issue number within the title of [Proxy] issues, so you can use "control F" in the browser to check if that proxy already exists.
