### ISSUE TITLE
Simplify the topic creation

### ISSUE THREAD

**Issue by ruKurz** [assistify/Rocket.Chat#73]
<img width="622" alt="bildschirmfoto_2017-09-29_um_08_10_31" src="https://user-images.githubusercontent.com/853776/31003297-3bce0492-a4ef-11e7-958b-e115cebe3008.png">

**Comment by ruKurz** [comment]
@all what do you think is this a good idea?

**Comment by mrsimpson** [comment]
@ruKurz I doubt that this is possible - from a business perspective:
A topic (fka. "expertise") does not just arise since someone has a related question. It's the other way round: Experts one one topic decide they want to support it via Assistify. Unless there are experts, there's no expertise ;)

**Comment by ruKurz** [comment]
Good point. Does the creation of a topic and starting a request differ? My aim would be simplify the creation. Since the thread based channels are planned, I will close that issue now.
