### ISSUE TITLE
Get statistics API

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#89]
As admin I want to get the statistics (_admin/info_) via an API so that I am able to crunch the data.

Note: See function _getStatistics()

**Comment by mrsimpson** [comment]
This should definitely be contributed to RC.
I'm quite sure, an explicit endpoint should be provided - maybe even with an own permission.

**Comment by graywolf336** [comment]
https://github.com/assistify/Rocket.Chat/blob/cd61929be75764e68f320e2684de105a27eda957/packages/rocketchat-api/server/v1/stats.js#L1-L17

This is currently possible by getting `GET api/v1/statistics` which will refresh and return the new result or `GET api/v1/statistics.list` which will return the history of them.

**Comment by janrudolph** [comment]
Awesome. Works pretty good. Thank you @graywolf336 !

**Comment by mrsimpson** [comment]
<img width="783" alt="smb" src="https://user-images.githubusercontent.com/17176678/31534178-1ee1873e-aff6-11e7-8d7f-eebd1337766d.png">

**Comment by janrudolph** [comment]
@graywolf336 One question regarding the statistics: How is an active user defined in Rocket.Chat?
