### ISSUE TITLE
Add channel for admin notifications

### ISSUE THREAD

**Issue by janrudolph** [assistify/Rocket.Chat#95]
Admins and managers should know what is going on in their teams. In some cases, they have to react on special events, e.g. an user has created a new account and needs to be verified through an admin. Currently, the admins do not get any notifications about such events. 

Since we provide a message platform, it does not make sense to send admin notifications about such events by email. Moreover, a bot should post a message to a channel and asks the admin to take action. 

This story is about creating an admin channel, invite admins and post information about a new created user by a bot in the channel. In the end, such channel may act as admin dashboard.

**Comment by mrsimpson** [comment]
Nice idea! Which events should be considered?

**Comment by janrudolph** [comment]
First admins should be notified when a new user has registered itself. Because the admin has to activate the user in this situation. Currently the admin does not receive any notification in this case. 

Other cases:
- creation of new public channels
- ...

**Comment by graywolf336** [comment]
If you want, you could use integrations to do this. Outgoing integrations allow more events than just sending a message and can be scripted to not have to go outside of the Rocket.Chat server:
* Message Sent
* File Uploaded
* Room Archived
* Room Created (public and private)
* User Joined Room
* User Left Room
* User Created

**Comment by mrsimpson** [comment]
👍 
I guess we have to debug though in order to know the load passed on each of those events - or is it documented anywhere else except in the source code?

**Comment by mrsimpson** [comment]
And what’s the api to write a message to a local room?

**Comment by graywolf336** [comment]
You could assign the room where the notifications should go when creating the outgoing integration.

Here is an example which will send a simple message with the room creator's username and the room's name:

```js
class Script {
  prepare_outgoing_request({ request }) {
    return {
      message: {
        text: `_${request.data.owner.username} created a room named "${request.data.room.name}"_`
      }
    };
  }
}
```

As far as the payload being passed to the script, it is only in the source code however it is fairly simple to understand:

https://github.com/assistify/Rocket.Chat/blob/11b4b7d922980e67dcd77108378345eb10ed002d/packages/rocketchat-integrations/server/lib/triggerHandler.js#L374-L454

**Comment by mrsimpson** [comment]
Ah, my bad! It didn’t appear to me prepare... could also return a value which is considered a response to be pared to a channel. 
👍
Still, with respect to debugging, i18n and stability I’d expect that to be a primer for a Rocketlet ;-)

**Comment by graywolf336** [comment]
Yeah, the message object can take `channel` which is a string or an array of the channels where to send the message to.

Yes, you are extremely correct. This would be a regular usage of a Rocketlet :stuck_out_tongue_winking_eye:

**Comment by crsCR** [comment]
So, right now there is no way for admin to know if a new user has signed up when 'manually approve new users' is on? No notification, no marker under User in Administration? Can you even search for inactive users somehow?
